import { NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import OpenAI from "openai";

export async function POST(req: Request) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const {
      productName,
      targetAudience,
      framework = "AIDA",
      platform = "Meta",
      brandVoice = "Empowering, friendly, direct",
      uniqueSellingPoint = "All-in-one simplicity without monthly tool fatigue",
    } = await req.json();

    const apiKey = process.env.OPENAI_API_KEY || process.env.DEEPSEEK_API_KEY;

    // Fallback generator if no key is present in environment
    if (!apiKey) {
      const fallbackTemplates: Record<string, { headline: string; rawAiCopy: string; callToAction: string }> = {
        AIDA: {
          headline: `Tired of juggling 10 different marketing tools for ${productName || "your business"}?`,
          rawAiCopy: `Attention: Most online entrepreneurs lose 15+ hours a week lost in tab fatigue.\n\nInterest: ${productName || "Our solution"} brings your media library, copy vault, scheduling, and analytics into one seamless command center.\n\nDesire: Imagine launching high-converting campaigns across Meta, Pinterest, and TikTok in under 10 minutes without guessing aspect ratios or lost files.\n\nAction: Claim your free 14-day trial today and reclaim your focus!`,
          callToAction: "Start Your Free Trial Now",
        },
        PAS: {
          headline: `Stop Burning Ad Dollars on Unoptimized ${platform} Ads`,
          rawAiCopy: `Problem: High ad spend with low conversions is the #1 dream killer for ${targetAudience || "aspiring marketers"}.\n\nAgitate: You spent days designing ads, only to get flagged for bad aspect ratios or weak hooks.\n\nSolution: ${productName || "Campaign Manager"} automatically validates your asset specs, pairs winning swipe headlines, and alerts you before your budget bleeds out.`,
          callToAction: "Get Started Risk-Free",
        },
        FAB: {
          headline: `Transform How You Create & Track Campaigns Forever`,
          rawAiCopy: `Feature: Integrated Media Asset Vault & Dynamic Aspect Ratio Prompter.\nAdvantage: Never post a square 1:1 image on 9:16 Pinterest or Reels again.\nBenefit: Enjoy 35% higher organic engagement and instant visual polish that commands authority in front of ${targetAudience || "your prospective buyers"}.`,
          callToAction: "Unlock Complete Access",
        },
      };

      const selectedFallback = fallbackTemplates[framework] || fallbackTemplates["AIDA"];

      return NextResponse.json({
        success: true,
        isFallback: true,
        framework,
        platform,
        headline: selectedFallback.headline,
        rawAiCopy: selectedFallback.rawAiCopy,
        callToAction: selectedFallback.callToAction,
        humanTouchPrompt: "👉 AI Draft ready! Add your personal founder story, a specific client testimonial, or your unique philosophy above before publishing.",
      });
    }

    // Call OpenAI / DeepSeek API when key exists
    const openai = new OpenAI({
      apiKey,
      baseURL: process.env.DEEPSEEK_BASE_URL || undefined,
    });

    const systemPrompt = `You are an expert direct-response copywriter and marketing campaign strategist. 
Generate compelling, high-converting ad copy for ${platform} using the ${framework} framework.
Target Audience: ${targetAudience}
Brand Voice: ${brandVoice}
Key Offer/USP: ${uniqueSellingPoint}`;

    const userPrompt = `Write an ad copy for ${productName}. Return JSON with: "headline", "rawAiCopy", "callToAction".`;

    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      response_format: { type: "json_object" },
    });

    const parsed = JSON.parse(response.choices[0].message.content || "{}");

    return NextResponse.json({
      success: true,
      isFallback: false,
      framework,
      platform,
      headline: parsed.headline || `High-Converting ${framework} Framework for ${productName}`,
      rawAiCopy: parsed.rawAiCopy || parsed.copy || "Draft content generated by AI Co-Pilot.",
      callToAction: parsed.callToAction || "Learn More Today",
      humanTouchPrompt: "👉 AI Draft ready! Add your personal founder story, a specific client testimonial, or your unique philosophy above before publishing.",
    });
  } catch (error: any) {
    console.error("AI Copilot Error:", error);
    return NextResponse.json({ error: error.message || "Failed to generate AI copy" }, { status: 500 });
  }
}
