export interface MarketCategory {
    label: string;
    tag: string;
    sector: string;
    suggestion: string;
    searchIntent?: string;
}

export const MARKET_CATEGORIES: MarketCategory[] = [
    { label: "Restaurants", tag: 'amenity=restaurant', sector: "Dining & Beverage", suggestion: "Launch a themed bistro or family diner." },
    { label: "Coffee Shops / Cafes", tag: 'amenity=cafe', sector: "Dining & Beverage", suggestion: "Open a boutique roastery or coworking cafe." },
    { label: "Grocery Stores", tag: 'shop=supermarket', sector: "Essential Retail", suggestion: "Start a specialty organic or local-first market." },
    { label: "Pharmacies", tag: 'amenity=pharmacy', sector: "Essential Retail", suggestion: "Establish a neighborhood compounding pharmacy." },
    { label: "Gas Stations", tag: 'amenity=fuel', sector: "Essential Retail", suggestion: "Build a modern EV charging & convenience hub." },
    { label: "Auto Repair", tag: 'shop=car_repair', sector: "Transport & Logistics", suggestion: "Specialize in hybrid/EV maintenance services." },
    { label: "Hair Salons", tag: 'shop=hairdresser', sector: "Personal Care", suggestion: "Create a premium grooming or color-specialist studio." },
    { label: "Fast Food", tag: 'amenity=fast_food', sector: "Dining & Beverage", suggestion: "Introduce a healthy, 'grab-and-go' quick service concept." },
    { label: "Banks", tag: 'amenity=bank', sector: "Professional Services", suggestion: "Open a community credit union or boutique advisory." },
    { label: "ATMs", tag: 'amenity=atm', sector: "Professional Services", suggestion: "Deploy secure, high-traffic mobile ATM kiosks." },
    { label: "Medical Clinics", tag: 'amenity=clinic', sector: "Health & Wellness", suggestion: "Start a specialized pediatrics or wellness clinic." },
    { label: "Dentists", tag: 'amenity=dentist', sector: "Health & Wellness", suggestion: "Establish a family-focused aesthetic dental practice." },
    { label: "Urgent Care", tag: 'amenity=hospital', sector: "Health & Wellness", suggestion: "Launch a 24/7 retail-based urgent care center." },
    { label: "Hotels", tag: 'tourism=hotel', sector: "Lifestyle & Leisure", suggestion: "Develop a boutique 'smart-stay' or eco-tourism lodge." },
    { label: "Pizza", tag: 'amenity=pizzeria', sector: "Dining & Beverage", suggestion: "Perfect an artisan wood-fired or delivery-only brand." },
    { label: "Clothing Stores", tag: 'shop=clothes', sector: "Lifestyle & Leisure", suggestion: "Open a curated sustainable fashion or vintage boutique." },
    { label: "Gyms", tag: 'leisure=fitness_centre', sector: "Health & Wellness", suggestion: "Found a HIIT studio or holistic recovery center." },
    { label: "Pet Stores", tag: 'shop=pet', sector: "Lifestyle & Leisure", suggestion: "Start a premium raw-diet or holistic pet wellness store." },
    { label: "Hardware Stores", tag: 'shop=hardware', sector: "Home & Trade", suggestion: "Establish a DIY-focused neighborhood hardware hub." },
    { label: "Convenience Stores", tag: 'shop=convenience', sector: "Essential Retail", suggestion: "Launch an autonomous, 24/7 smart convenience kiosk." },
    { label: "Bakeries", tag: 'shop=bakery', sector: "Dining & Beverage", suggestion: "Specialize in sourdough or gluten-free artisan breads." },
    { label: "Insurance", tag: 'office=insurance', sector: "Professional Services", suggestion: "Offer niche digital-first personal asset insurance." },
    { label: "Real Estate", tag: 'office=estate_agent', sector: "Professional Services", suggestion: "Focus on relocation services for remote workers." },
    { label: "Lawyers", tag: 'office=lawyer', sector: "Professional Services", suggestion: "Specialize in tech-focused IP or estate protection." },
    { label: "Child Care", tag: 'amenity=kindergarten', sector: "Lifestyle & Leisure", suggestion: "Open a Montessori-inspired early learning center." },
    { label: "Spas", tag: 'amenity=spa', sector: "Personal Care", suggestion: "Create a Japanese-style head spa or wellness sanctuary." },
    { label: "Electronics", tag: 'shop=electronics', sector: "Lifestyle & Leisure", suggestion: "Establish a premium repair and smart-home config shop." },
    { label: "Cleaning Services", tag: 'shop=cleaning', sector: "Home & Trade", suggestion: "Launch an eco-friendly 'green' residential cleaning brand." },
    { label: "Plumbers", tag: 'craft=plumber', sector: "Home & Trade", suggestion: "Provide smart leak detection and high-efficiency plumbing." },
    { label: "Electricians", tag: 'craft=electrician', sector: "Home & Trade", suggestion: "Focus on home solar and EV charger installations." },
    { label: "HVAC", tag: 'craft=hvac', sector: "Home & Trade", suggestion: "Specialize in energy-saving heat pump retrofits." },
    { label: "Landscaping", tag: 'craft=gardener', sector: "Home & Trade", suggestion: "Offer native-plant garden design and drought-proofing." },
    { label: "Movers", tag: 'office=moving_company', sector: "Transport & Logistics", suggestion: "Specialize in white-glove 'senior relocation' services." },
    { label: "Towing", tag: 'amenity=towing', sector: "Transport & Logistics", suggestion: "Establish a 24/7 smart-dispatch towing fleet." },
    { label: "Locksmiths", tag: 'shop=locksmith', sector: "Home & Trade", suggestion: "Focus on smart-lock conversions and high-security entry." },
    { label: "Pest Control", tag: 'office=pest_control', sector: "Home & Trade", suggestion: "Provide modern, pet-safe organic pest management." },
    { label: "Car Wash", tag: 'amenity=car_wash', sector: "Transport & Logistics", suggestion: "Open a water-recycling touchless or ceramic-coating hub." },
    { label: "Florists", tag: 'shop=florist', sector: "Lifestyle & Leisure", suggestion: "Create a subscription-based floral design studio." },
    { label: "Bookstores", tag: 'shop=books', sector: "Lifestyle & Leisure", suggestion: "Build a community niche bookstore with coffee & events." },
    { label: "Jewelry", tag: 'shop=jewelry', sector: "Lifestyle & Leisure", suggestion: "Offer custom lab-grown diamond and repair services." },
    { label: "Optometrists", tag: 'shop=optician', sector: "Health & Wellness", suggestion: "Open a designer-frame focused boutique eye clinic." },
    { label: "Physical Therapy", tag: 'healthcare=physical_therapist', sector: "Health & Wellness", suggestion: "Focus on sports performance and mobility coaching." },
    { label: "Chiropractors", tag: 'healthcare=chiropractor', sector: "Health & Wellness", suggestion: "Specialize in workplace ergonomics and posture care." },
    { label: "Massage", tag: 'amenity=massage', sector: "Health & Wellness", suggestion: "Establish a therapeutic sports or deep-tissue studio." },
    { label: "Tax Prep", tag: 'office=tax', sector: "Professional Services", suggestion: "Provide AI-assisted crypto and small business tax help." },
    { label: "Accountants", tag: 'office=accountant', sector: "Professional Services", suggestion: "Focus on outsourced CFO services for startups." },
    { label: "Print & Copy", tag: 'shop=copy', sector: "Lifestyle & Leisure", suggestion: "Build a premium large-format and brand-identity lab." },
    { label: "Laundromats", tag: 'amenity=laundry', sector: "Lifestyle & Leisure", suggestion: "Open a modern 'laundry-lounge' with cafe & Wi-Fi." },
    { label: "Party Supply", tag: 'shop=party_supplies', sector: "Lifestyle & Leisure", suggestion: "Specialize in high-end event decor and rentals." },
    { label: "Bike Shops", tag: 'shop=bicycle', sector: "Transport & Logistics", suggestion: "Start an e-bike specialist sales and service hub." },
];
