export const WHOLESALE_CATEGORIES = [
    "Art",
    "Baby & Maternity",
    "Books, Movies & Media",
    "Business & Industrial",
    "Clothing, Shoes & Accessories",
    "Collectibles",
    "Computers & Networking",
    "Consumer Electronics",
    "Crafts & Supplies",
    "Food & Drinks",
    "Health & Beauty",
    "Home & Garden",
    "Jewelry & Watches",
    "Mature Audiences 18+",
    "Music & Instruments",
    "Office & School Supplies",
    "Pet Supplies",
    "Special Occasions & Party",
    "Sporting Goods",
    "Supplements & Nutrition",
    "Tools & Hardware",
    "Toys, Games & Hobbies",
    "Travel",
    "Vehicles, Parts & Accessories"
];
