export interface Copywriter100 {
  id: string;
  name: string;
  archetype: "Direct Response Legends" | "Digital Funnel Architects" | "SaaS & Conversion Specialists" | "Brand & Storytelling Gurus" | "Modern AI & Niche Innovators";
  sampleVoice: string;
  focus: string;
  stylePreset: "The Legend" | "The Funnel Hacker" | "The Data Scientist" | "The Storyteller" | "The AI Innovator";
  keyConcept: string;
  promptPrefix: string;
}

export interface StylePreset {
  id: "The Legend" | "The Funnel Hacker" | "The Data Scientist" | "The Storyteller" | "The AI Innovator";
  name: string;
  tagline: string;
  description: string;
  primaryInfluencers: string[];
  toneModifier: string;
  badgeColor: string;
}

export const fontStylePresets: StylePreset[] = [
  {
    id: "The Legend",
    name: "The Legend Mode (Caples / Ogilvy)",
    tagline: "Formal, Headline-Focused & Evidence-Based",
    description: "Channels classic direct response masters like Ogilvy & Caples. Uses long-form prestige facts, tested proof, and curious headlines.",
    primaryInfluencers: ["David Ogilvy", "John Caples", "Claude Hopkins", "Gary Halbert", "Eugene Schwartz"],
    toneModifier: "🏛️ [Legend Style - Tested Proof & Fact Precision]: ",
    badgeColor: "amber",
  },
  {
    id: "The Funnel Hacker",
    name: "The Funnel Hacker Mode (Brunson / Kern)",
    tagline: "High-Energy, Story-Driven & Urgency-Heavy",
    description: "Channels modern funnel architects like Brunson & Kern. Built around Hook-Story-Offer, VSLs, and rapid launch momentum.",
    primaryInfluencers: ["Russell Brunson", "Frank Kern", "Dan Kennedy", "Jeff Walker", "Stefan Georgi"],
    toneModifier: "🚀 [Funnel Hacker Style - High Energy Hook-Story-Offer]: ",
    badgeColor: "purple",
  },
  {
    id: "The Data Scientist",
    name: "The Data Scientist Mode (Wiebe / Dean)",
    tagline: "Clear, Voice-of-Customer & Conversion-Focused",
    description: "Channels conversion & SEO experts like Joanna Wiebe & Brian Dean. Relies on data, customer quotes, and friction-free clarity.",
    primaryInfluencers: ["Joanna Wiebe", "Brian Dean", "Peep Laja", "Neil Patel", "Oli Gardner"],
    toneModifier: "📊 [Data Scientist Style - Voice of Customer & Precise Clarity]: ",
    badgeColor: "blue",
  },
  {
    id: "The Storyteller",
    name: "The Storyteller Mode (Godin / Miller)",
    tagline: "Empathetic, Brand-Focused & Purpose-Driven",
    description: "Channels brand narrative masters like Seth Godin & Donald Miller. Focuses on reader empathy, clarity, and the hero's journey.",
    primaryInfluencers: ["Seth Godin", "Donald Miller", "Simon Sinek", "Marie Forleo", "James Clear"],
    toneModifier: "💖 [Storyteller Style - Empathetic Brand Narrative]: ",
    badgeColor: "rose",
  },
  {
    id: "The AI Innovator",
    name: "The AI Innovator Mode (Modern / Hormozi)",
    tagline: "Efficient, Grand-Slam Value & Future-Forward",
    description: "Channels modern growth hackers like Alex Hormozi & AI innovators. Uses no-nonsense value stacking, speed, and grand slam offers.",
    primaryInfluencers: ["Alex Hormozi", "Grant Cardone", "Ethan Brooks", "Matt Wolfe", "Ramit Sethi"],
    toneModifier: "⚡ [AI Innovator Style - Grand-Slam Value & Automation Speed]: ",
    badgeColor: "emerald",
  },
];

export const TOP_100_COPYWRITERS: Copywriter100[] = [
  // ARCHETYPE 1: THE DIRECT RESPONSE LEGENDS (1 - 15)
  {
    id: "ogilvy",
    name: "David Ogilvy",
    archetype: "Direct Response Legends",
    sampleVoice: "At 60 miles an hour the loudest noise in this new Rolls-Royce comes from the electric clock.",
    focus: "Headlines, long-form sales letters, prestige brand image",
    stylePreset: "The Legend",
    keyConcept: "Tell the truth, but make the truth fascinating and brand-safe.",
    promptPrefix: "👑 [David Ogilvy Style]: ",
  },
  {
    id: "caples",
    name: "John Caples",
    archetype: "Direct Response Legends",
    sampleVoice: "They Laughed When I Sat Down at the Piano – But When I Began to Play!",
    focus: "Curiosity-driven headlines, tested direct response",
    stylePreset: "The Legend",
    keyConcept: "Test everything. Appeal to self-interest and curiosity.",
    promptPrefix: "🔥 [John Caples Style]: ",
  },
  {
    id: "hopkins",
    name: "Claude Hopkins",
    archetype: "Direct Response Legends",
    sampleVoice: "Why Some Foods 'Explode' in Your Stomach.",
    focus: "Scientific advertising & reason-why copy",
    stylePreset: "The Legend",
    keyConcept: "Offer specific reason-why reasons to buy.",
    promptPrefix: "💡 [Claude Hopkins Style]: ",
  },
  {
    id: "halbert",
    name: "Gary Halbert",
    archetype: "Direct Response Legends",
    sampleVoice: "Do You Make These Mistakes in English?",
    focus: "Conversational, urgent, personal storytelling",
    stylePreset: "The Legend",
    keyConcept: "Write like you talk to a close friend at a bar.",
    promptPrefix: "📣 [Gary Halbert Style]: ",
  },
  {
    id: "martin",
    name: "Mel Martin",
    archetype: "Direct Response Legends",
    sampleVoice: "The Wall Street Journal Letter",
    focus: "Narrative, bullet fascinations, secret teasers",
    stylePreset: "The Legend",
    keyConcept: "Tease the benefit without revealing the secret until they buy.",
    promptPrefix: "✨ [Mel Martin Style]: ",
  },
  {
    id: "schwartz",
    name: "Eugene Schwartz",
    archetype: "Direct Response Legends",
    sampleVoice: "Breakthrough Advertising",
    focus: "Market awareness levels & sophistication",
    stylePreset: "The Legend",
    keyConcept: "Channel existing market desires into your offer.",
    promptPrefix: "🌟 [Eugene Schwartz Style]: ",
  },
  {
    id: "sugarman",
    name: "Joseph Sugarman",
    archetype: "Direct Response Legends",
    sampleVoice: "The BluBlocker Sales Letter",
    focus: "Slippery slide technique & psychological triggers",
    stylePreset: "The Legend",
    keyConcept: "Every element must make the reader read the next line.",
    promptPrefix: "🕶️ [Joseph Sugarman Style]: ",
  },
  {
    id: "collier",
    name: "Robert Collier",
    archetype: "Direct Response Legends",
    sampleVoice: "Secrets of Mental Magic",
    focus: "Psychological depth & entering the conversation in the prospect's mind",
    stylePreset: "The Legend",
    keyConcept: "Enter the conversation already taking place in the customer's mind.",
    promptPrefix: "🧠 [Robert Collier Style]: ",
  },
  {
    id: "schwab",
    name: "Victor Schwab",
    archetype: "Direct Response Legends",
    sampleVoice: "How to Win Friends and Influence People",
    focus: "Headline mastery & benefit stacking",
    stylePreset: "The Legend",
    keyConcept: "Show what your product DOES, not what it IS.",
    promptPrefix: "📜 [Victor Schwab Style]: ",
  },
  {
    id: "burnett",
    name: "Leo Burnett",
    archetype: "Direct Response Legends",
    sampleVoice: "When it rains, it pours.",
    focus: "Visual metaphors & brand icons",
    stylePreset: "The Legend",
    keyConcept: "Find the inherent drama in every product.",
    promptPrefix: "🎨 [Leo Burnett Style]: ",
  },
  {
    id: "bernbach",
    name: "Bill Bernbach",
    archetype: "Direct Response Legends",
    sampleVoice: "Think Small.",
    focus: "Contrarian honesty & iconic simplicity",
    stylePreset: "The Legend",
    keyConcept: "Rules are what the artist breaks; the memorable never emerged from a formula.",
    promptPrefix: "🚗 [Bill Bernbach Style]: ",
  },
  {
    id: "reeves",
    name: "Rosser Reeves",
    archetype: "Direct Response Legends",
    sampleVoice: "Unique Selling Proposition (USP)",
    focus: "Single strong USP repetition",
    stylePreset: "The Legend",
    keyConcept: "Every ad must make a specific proposition that competitors cannot offer.",
    promptPrefix: "💎 [Rosser Reeves Style]: ",
  },
  {
    id: "sackheim",
    name: "Maxwell Sackheim",
    archetype: "Direct Response Legends",
    sampleVoice: "An Amazing Little Book...",
    focus: "Curiosity & book-club direct response",
    stylePreset: "The Legend",
    keyConcept: "Lead with curiosity and dramatic proof.",
    promptPrefix: "📚 [Maxwell Sackheim Style]: ",
  },
  {
    id: "conroy",
    name: "Martin Conroy",
    archetype: "Direct Response Legends",
    sampleVoice: "Two Young Men Came to Wall Street",
    focus: "Parable storytelling & long-term narrative",
    stylePreset: "The Legend",
    keyConcept: "Tell a compelling story of two people with different choices.",
    promptPrefix: "🏙️ [Martin Conroy Style]: ",
  },
  {
    id: "carlton",
    name: "John Carlton",
    archetype: "Direct Response Legends",
    sampleVoice: "Gun to the Head Copywriting",
    focus: "Aggressive, punchy, direct response",
    stylePreset: "The Legend",
    keyConcept: "Write with the urgency of having a gun to your head.",
    promptPrefix: "🎯 [John Carlton Style]: ",
  },

  // ARCHETYPE 2: THE DIGITAL FUNNEL ARCHITECTS (16 - 30)
  {
    id: "brunson",
    name: "Russell Brunson",
    archetype: "Digital Funnel Architects",
    sampleVoice: "Who else wants to build a funnel that converts?",
    focus: "Landing pages, value ladders & Hook-Story-Offer",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Hook their attention, tell your epiphany story, make a stack offer.",
    promptPrefix: "🚀 [Russell Brunson Style]: ",
  },
  {
    id: "kennedy",
    name: "Dan Kennedy",
    archetype: "Digital Funnel Architects",
    sampleVoice: "No B.S. Direct Marketing",
    focus: "Contrarian, value-based magnetic positioning",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Different is better than better. Take a bold stance.",
    promptPrefix: "🎯 [Dan Kennedy Style]: ",
  },
  {
    id: "kern",
    name: "Frank Kern",
    archetype: "Digital Funnel Architects",
    sampleVoice: "Behavioral Dynamic Response",
    focus: "Psychological VSLs & serialized story launches",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Help people by actually helping them in your videos.",
    promptPrefix: "🎬 [Frank Kern Style]: ",
  },
  {
    id: "deiss",
    name: "Ryan Deiss",
    archetype: "Digital Funnel Architects",
    sampleVoice: "Customer Value Journey",
    focus: "Systematic funnels & ethical lead acquisition",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Map out the customer journey step-by-step.",
    promptPrefix: "📈 [Ryan Deiss Style]: ",
  },
  {
    id: "walker",
    name: "Jeff Walker",
    archetype: "Digital Funnel Architects",
    sampleVoice: "Product Launch Formula",
    focus: "Event-based launch sequences & anticipation build-up",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Transform sales into an anticipated community event.",
    promptPrefix: "📅 [Jeff Walker Style]: ",
  },
  {
    id: "brown",
    name: "Todd Brown",
    archetype: "Digital Funnel Architects",
    sampleVoice: "Epiphany Bridge & E5 Method",
    focus: "Big Idea & unique mechanism marketing",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Lead with one single Big Idea and a clear mechanism.",
    promptPrefix: "💡 [Todd Brown Style]: ",
  },
  {
    id: "georgi",
    name: "Stefan Georgi",
    archetype: "Digital Funnel Architects",
    sampleVoice: "RMBC Method (Research, Mechanism, Brief, Copy)",
    focus: "Systematic VSL & sales letter speed writing",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Follow RMBC to guarantee high-converting VSL structure.",
    promptPrefix: "⚡ [Stefan Georgi Style]: ",
  },
  {
    id: "benson",
    name: "Jon Benson",
    archetype: "Digital Funnel Architects",
    sampleVoice: "Ugly Sales Letters (Ugly VSL Creator)",
    focus: "Simple text-on-screen VSL persuasion",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Simple ugly text on screen out-converts fancy videos.",
    promptPrefix: "📹 [Jon Benson Style]: ",
  },
  {
    id: "settle",
    name: "Ben Settle",
    archetype: "Digital Funnel Architects",
    sampleVoice: "Email Players (Daily Infotainment)",
    focus: "Daily polarizing email marketing",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Entertain first, educate second, sell every single day.",
    promptPrefix: "✉️ [Ben Settle Style]: ",
  },
  {
    id: "chaperon",
    name: "André Chaperon",
    archetype: "Digital Funnel Architects",
    sampleVoice: "Soap Opera Sequence",
    focus: "Episodic storytelling & open loops",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Hook readers with open loops that demand the next episode.",
    promptPrefix: "📺 [André Chaperon Style]: ",
  },
  {
    id: "orzechowski",
    name: "Chris Orzechowski",
    archetype: "Digital Funnel Architects",
    sampleVoice: "Orchestrated Email Campaigns",
    focus: "Clean, direct e-commerce email copy",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Write emails that sell without turning your list off.",
    promptPrefix: "💌 [Chris Orzechowski Style]: ",
  },
  {
    id: "furey",
    name: "Matt Furey",
    archetype: "Digital Funnel Architects",
    sampleVoice: "Cardinal Rules of List Building",
    focus: "Daily email list nurturing & direct response",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Your email list is your personal ATM.",
    promptPrefix: "💰 [Matt Furey Style]: ",
  },
  {
    id: "dillard",
    name: "Mike Dillard",
    archetype: "Digital Funnel Architects",
    sampleVoice: "Attraction Marketing",
    focus: "Inbound attraction & authority positioning",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Position yourself as the hunted, not the hunter.",
    promptPrefix: "🌟 [Mike Dillard Style]: ",
  },
  {
    id: "edwards",
    name: "Ray Edwards",
    archetype: "Digital Funnel Architects",
    sampleVoice: "Copywriting Secrets (PASTOR Framework)",
    focus: "Broadcasting style & PASTOR framework",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Person, Problem, Amplify, Story, Transformation, Offer, Response.",
    promptPrefix: "🎙️ [Ray Edwards Style]: ",
  },
  {
    id: "medhora",
    name: "Neville Medhora",
    archetype: "Digital Funnel Architects",
    sampleVoice: "Kopywriting Kourse",
    focus: "Simple, visual, beginner-friendly copy cleanups",
    stylePreset: "The Funnel Hacker",
    keyConcept: "Make your copy so simple a 5th grader gets excited.",
    promptPrefix: "✏️ [Neville Medhora Style]: ",
  },

  // ARCHETYPE 3: THE SAAS & CONVERSION SPECIALISTS (31 - 45)
  {
    id: "wiebe",
    name: "Joanna Wiebe",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "You’re not selling a drill; you’re selling a hole.",
    focus: "Voice-of-Customer research & SaaS landing pages",
    stylePreset: "The Data Scientist",
    keyConcept: "Copywriting is not writing; it is assembling customer words.",
    promptPrefix: "📊 [Joanna Wiebe Style]: ",
  },
  {
    id: "laja",
    name: "Peep Laja",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "Conversion Rate Experts & CXL",
    focus: "Data-driven A/B testing & CRO",
    stylePreset: "The Data Scientist",
    keyConcept: "Test everything based on empirical data, not opinions.",
    promptPrefix: "🧪 [Peep Laja Style]: ",
  },
  {
    id: "gardner",
    name: "Oli Gardner",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "Unbounce Landing Page Rules",
    focus: "Landing page conversion & visual hierarchy",
    stylePreset: "The Data Scientist",
    keyConcept: "One page, one goal, zero distraction.",
    promptPrefix: "🎯 [Oli Gardner Style]: ",
  },
  {
    id: "wolf_talia",
    name: "Talia Wolf",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "GetUplift Emotional Targeting",
    focus: "Emotional conversion & buyer psychology",
    stylePreset: "The Data Scientist",
    keyConcept: "People buy with emotion and justify with logic.",
    promptPrefix: "💖 [Talia Wolf Style]: ",
  },
  {
    id: "crestodina",
    name: "Andy Crestodina",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "Orbit Media Content Analytics",
    focus: "Content marketing data & SEO structure",
    stylePreset: "The Data Scientist",
    keyConcept: "The best content is structured around data and search intent.",
    promptPrefix: "📌 [Andy Crestodina Style]: ",
  },
  {
    id: "dean",
    name: "Brian Dean",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "Backlinko & Skyscraper Technique",
    focus: "SEO copywriting & actionable guides",
    stylePreset: "The Data Scientist",
    keyConcept: "Create content that is 10x better than the top result.",
    promptPrefix: "🔗 [Brian Dean Style]: ",
  },
  {
    id: "patel",
    name: "Neil Patel",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "Digital Marketing Guides",
    focus: "Comprehensive, keyword-rich SEO guides",
    stylePreset: "The Data Scientist",
    keyConcept: "Provide complete, exhaustive answers to high-volume keywords.",
    promptPrefix: "🌐 [Neil Patel Style]: ",
  },
  {
    id: "fishkin",
    name: "Rand Fishkin",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "SparkToro Audience Intelligence",
    focus: "Audience intelligence & empathetic marketing",
    stylePreset: "The Data Scientist",
    keyConcept: "Find where your audience hangs out and add genuine value there.",
    promptPrefix: "🔍 [Rand Fishkin Style]: ",
  },
  {
    id: "handley",
    name: "Ann Handley",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "Everybody Writes",
    focus: "Empathetic, professional content storytelling",
    stylePreset: "The Data Scientist",
    keyConcept: "Good writing is about clarity and empathy for the reader.",
    promptPrefix: "✍️ [Ann Handley Style]: ",
  },
  {
    id: "baer",
    name: "Jay Baer",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "Hug Your Haters",
    focus: "Customer service as marketing & Youtility",
    stylePreset: "The Data Scientist",
    keyConcept: "Make your marketing so useful people would pay for it.",
    promptPrefix: "🤗 [Jay Baer Style]: ",
  },
  {
    id: "sheridan",
    name: "Marcus Sheridan",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "They Ask, You Answer",
    focus: "Transparent inbound Q&A marketing",
    stylePreset: "The Data Scientist",
    keyConcept: "Answer every question your prospects have openly and honestly.",
    promptPrefix: "💬 [Marcus Sheridan Style]: ",
  },
  {
    id: "pulizzi",
    name: "Joe Pulizzi",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "Content Inc.",
    focus: "Content asset building & audience monetization",
    stylePreset: "The Data Scientist",
    keyConcept: "Build an audience first, then create products they ask for.",
    promptPrefix: "📖 [Joe Pulizzi Style]: ",
  },
  {
    id: "stelzner",
    name: "Michael Stelzner",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "Social Media Examiner",
    focus: "Platform-specific marketing reports",
    stylePreset: "The Data Scientist",
    keyConcept: "Provide industry benchmark insights to attract ideal clients.",
    promptPrefix: "📑 [Michael Stelzner Style]: ",
  },
  {
    id: "smith_mari",
    name: "Mari Smith",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "Social Media Strategy",
    focus: "Visual, engaging Facebook & social strategy",
    stylePreset: "The Data Scientist",
    keyConcept: "Combine video, storytelling, and warm engagement.",
    promptPrefix: "📱 [Mari Smith Style]: ",
  },
  {
    id: "kawasaki",
    name: "Guy Kawasaki",
    archetype: "SaaS & Conversion Specialists",
    sampleVoice: "Art of the Start & Evangelism",
    focus: "Product evangelism & pitch decks",
    stylePreset: "The Data Scientist",
    keyConcept: "Enchant your users so they become your loudest advocates.",
    promptPrefix: "✨ [Guy Kawasaki Style]: ",
  },

  // ARCHETYPE 4: THE BRAND & STORYTELLING GURUS (46 - 60)
  {
    id: "godin",
    name: "Seth Godin",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "Permission Marketing & Purple Cow",
    focus: "Philosophical, short, tribal brand marketing",
    stylePreset: "The Storyteller",
    keyConcept: "Don't find customers for your products; find products for your customers.",
    promptPrefix: "🐂 [Seth Godin Style]: ",
  },
  {
    id: "sinek",
    name: "Simon Sinek",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "Start with Why",
    focus: "Purpose-driven brand messaging & leadership",
    stylePreset: "The Storyteller",
    keyConcept: "People don't buy what you do; they buy why you do it.",
    promptPrefix: "🎯 [Simon Sinek Style]: ",
  },
  {
    id: "miller",
    name: "Donald Miller",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "Building a StoryBrand",
    focus: "Hero's Journey brand frameworks",
    stylePreset: "The Storyteller",
    keyConcept: "Your customer is the hero; your brand is the guide.",
    promptPrefix: "🏰 [Donald Miller Style]: ",
  },
  {
    id: "jiwa",
    name: "Bernadette Jiwa",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "The Storyteller's Secret",
    focus: "Meaningful brand narratives & emotional resonance",
    stylePreset: "The Storyteller",
    keyConcept: "Marketing is no longer about the stuff you make, but the stories you tell.",
    promptPrefix: "✨ [Bernadette Jiwa Style]: ",
  },
  {
    id: "nichols",
    name: "Lisa Nichols",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "Speak to Sell",
    focus: "Transformational storytelling & keynote persuasion",
    stylePreset: "The Storyteller",
    keyConcept: "Share your scars, not your wounds, to inspire action.",
    promptPrefix: "🎙️ [Lisa Nichols Style]: ",
  },
  {
    id: "forleo",
    name: "Marie Forleo",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "B-School & Everything is Figureoutable",
    focus: "Empowering, friendly, high-energy brand copy",
    stylePreset: "The Storyteller",
    keyConcept: "Everything is figureoutable when you stay true to your purpose.",
    promptPrefix: "💃 [Marie Forleo Style]: ",
  },
  {
    id: "porterfield",
    name: "Amy Porterfield",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "Digital Course Academy",
    focus: "Step-by-step, warm, friendly educational marketing",
    stylePreset: "The Storyteller",
    keyConcept: "Teach everything you know to build unconditional trust.",
    promptPrefix: "🎧 [Amy Porterfield Style]: ",
  },
  {
    id: "flynn",
    name: "Pat Flynn",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "Smart Passive Income",
    focus: "Transparent, trustworthy, affiliate income reports",
    stylePreset: "The Storyteller",
    keyConcept: "Serve first, and the income will follow naturally.",
    promptPrefix: "💡 [Pat Flynn Style]: ",
  },
  {
    id: "ferriss",
    name: "Tim Ferriss",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "4-Hour Workweek",
    focus: "Lifestyle design, experimental hacking & bullet breakdowns",
    stylePreset: "The Storyteller",
    keyConcept: "Test the extreme edge of efficiency and question assumptions.",
    promptPrefix: "⏳ [Tim Ferriss Style]: ",
  },
  {
    id: "clear",
    name: "James Clear",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "Atomic Habits",
    focus: "Small changes, punchy newsletter breakdowns",
    stylePreset: "The Storyteller",
    keyConcept: "Focus on 1% daily improvements and systems over goals.",
    promptPrefix: "⚛️ [James Clear Style]: ",
  },
  {
    id: "manson",
    name: "Mark Manson",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "Subtle Art of Not Giving a F*ck",
    focus: "Blunt, honest, contrarian self-help",
    stylePreset: "The Storyteller",
    keyConcept: "Cut through fluff with radical, honest authenticity.",
    promptPrefix: "⚡ [Mark Manson Style]: ",
  },
  {
    id: "brown_brene",
    name: "Brené Brown",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "Dare to Lead",
    focus: "Vulnerability, courage, empathetic leadership",
    stylePreset: "The Storyteller",
    keyConcept: "Vulnerability is not weakness; it is our greatest measure of courage.",
    promptPrefix: "❤️ [Brené Brown Style]: ",
  },
  {
    id: "vaynerchuk",
    name: "Gary Vaynerchuk",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "Jab, Jab, Jab, Right Hook",
    focus: "Volume value, raw hustle, native social media hooks",
    stylePreset: "The Storyteller",
    keyConcept: "Give value 3 times before ever asking for a sale.",
    promptPrefix: "🥊 [Gary Vaynerchuk Style]: ",
  },
  {
    id: "hogshead",
    name: "Sally Hogshead",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "Fascinate",
    focus: "Personality branding & 7 fascination triggers",
    stylePreset: "The Storyteller",
    keyConcept: "Different is better than better. Fascination is instant interest.",
    promptPrefix: "🌟 [Sally Hogshead Style]: ",
  },
  {
    id: "clark_dorie",
    name: "Dorie Clark",
    archetype: "Brand & Storytelling Gurus",
    sampleVoice: "Stand Out",
    focus: "Thought leadership & expert positioning",
    stylePreset: "The Storyteller",
    keyConcept: "Find your niche idea and build a long-term reputation.",
    promptPrefix: "🎓 [Dorie Clark Style]: ",
  },

  // ARCHETYPE 5: THE MODERN AI & NICHE INNOVATORS (61 - 100)
  {
    id: "hormozi",
    name: "Alex Hormozi",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "$100M Offers & $100M Leads",
    focus: "Grand Slam Offers, value stacking & simple diagrams",
    stylePreset: "The AI Innovator",
    keyConcept: "Make an offer so good people feel stupid saying no.",
    promptPrefix: "⚡ [Alex Hormozi Style]: ",
  },
  {
    id: "cardone",
    name: "Grant Cardone",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "10X Rule",
    focus: "Aggressive, high-energy sales push",
    stylePreset: "The AI Innovator",
    keyConcept: "Take 10X more action than anyone else in your space.",
    promptPrefix: "🔥 [Grant Cardone Style]: ",
  },
  {
    id: "ramit",
    name: "Ramit Sethi",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "I Will Teach You to Be Rich",
    focus: "Direct, no-nonsense financial & course sales",
    stylePreset: "The AI Innovator",
    keyConcept: "Focus on $30,000 questions, not $3 lattes.",
    promptPrefix: "💵 [Ramit Sethi Style]: ",
  },
  {
    id: "brooks",
    name: "Ethan Brooks",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "AI for Marketing",
    focus: "Practical AI prompt engineering for copywriters",
    stylePreset: "The AI Innovator",
    keyConcept: "Treat AI as your co-pilot, not a lazy replacement.",
    promptPrefix: "🤖 [Ethan Brooks AI Style]: ",
  },
  {
    id: "wolfe",
    name: "Matt Wolfe",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Future Tools",
    focus: "AI tool reviews & rapid workflow automation",
    stylePreset: "The AI Innovator",
    keyConcept: "Leverage cutting-edge AI tools to 10x output speed.",
    promptPrefix: "🛠️ [Matt Wolfe AI Style]: ",
  },
  {
    id: "miller_allie",
    name: "Allie K. Miller",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "AI Business Strategy",
    focus: "Practical enterprise AI application",
    stylePreset: "The AI Innovator",
    keyConcept: "Implement AI solutions that directly impact bottom-line metrics.",
    promptPrefix: "💻 [Allie K. Miller Style]: ",
  },
  {
    id: "hubspot",
    name: "HubSpot Academy",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Inbound Marketing Engine",
    focus: "Educational inbound marketing & lead magnets",
    stylePreset: "The AI Innovator",
    keyConcept: "Attract, engage, and delight customers with educational content.",
    promptPrefix: "🧡 [HubSpot Style]: ",
  },
  {
    id: "belgray",
    name: "Laura Belgray",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Talking Shrimp",
    focus: "Quirky, personality-driven email copy",
    stylePreset: "The AI Innovator",
    keyConcept: "Inject weird personality into every email you write.",
    promptPrefix: "🦐 [Laura Belgray Style]: ",
  },
  {
    id: "goff",
    name: "Justin Goff",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Offer Creation & Direct Response",
    focus: "Health & Supplement direct response offer stacking",
    stylePreset: "The AI Innovator",
    keyConcept: "Stack undeniable bonuses and proof on your front-end offer.",
    promptPrefix: "💊 [Justin Goff Style]: ",
  },
  {
    id: "ovens",
    name: "Sam Ovens",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Consulting.com & Skool",
    focus: "First-principles simplicity & diagram sales copy",
    stylePreset: "The AI Innovator",
    keyConcept: "Strip away complexity until only pure first-principles remain.",
    promptPrefix: "📐 [Sam Ovens Style]: ",
  },
  {
    id: "hormozi_leila",
    name: "Leila Hormozi",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Acquisition.com Operations",
    focus: "Direct business operations & leadership copy",
    stylePreset: "The AI Innovator",
    keyConcept: "Focus on execution, talent acquisition, and operational clarity.",
    promptPrefix: "🏢 [Leila Hormozi Style]: ",
  },
  {
    id: "sykes",
    name: "Tim Sykes",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Stock Trading Urgency",
    focus: "High-urgency proof & fast-action alerts",
    stylePreset: "The AI Innovator",
    keyConcept: "Show live trade proof and urgent limited-seat alerts.",
    promptPrefix: "📉 [Tim Sykes Style]: ",
  },
  {
    id: "lopez",
    name: "Tai Lopez",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Knowledge & Garage Video Hooks",
    focus: "Curiosity hooks & lifestyle proof",
    stylePreset: "The AI Innovator",
    keyConcept: "Here in my garage... curiosity hooks combined with book takeaways.",
    promptPrefix: "🏎️ [Tai Lopez Style]: ",
  },
  {
    id: "ruffino",
    name: "Russell Ruffino",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Clients on Demand",
    focus: "High-ticket webinar funnels & direct closing",
    stylePreset: "The AI Innovator",
    keyConcept: "Sell high-ticket services via a single 45-minute presentation.",
    promptPrefix: "📞 [Russell Ruffino Style]: ",
  },
  {
    id: "koeppel",
    name: "Peter Koeppel",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Direct Response TV & Online",
    focus: "Multi-channel direct response campaigns",
    stylePreset: "The AI Innovator",
    keyConcept: "Combine broadcast media hooks with digital instant response.",
    promptPrefix: "📺 [Peter Koeppel Style]: ",
  },
  {
    id: "gandia",
    name: "Ed Gandia",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "High-Income Freelance Copywriting",
    focus: "B2B copy pricing & client acquisition",
    stylePreset: "The AI Innovator",
    keyConcept: "Position yourself as a strategic business partner, not a wordsmith.",
    promptPrefix: "💼 [Ed Gandia Style]: ",
  },
  {
    id: "rogers",
    name: "Kevin Rogers",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Copy Chief 60-Second Sales Hook",
    focus: "Stand-up comedy storytelling & 60-second hooks",
    stylePreset: "The AI Innovator",
    keyConcept: "Use stand-up timing to hook readers in under 60 seconds.",
    promptPrefix: "🎭 [Kevin Rogers Style]: ",
  },
  {
    id: "cutcliffe",
    name: "Colleen Cutcliffe",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Biotech & Health Science",
    focus: "Science-backed health product copywriting",
    stylePreset: "The AI Innovator",
    keyConcept: "Translate complex clinical science into simple daily benefits.",
    promptPrefix: "🧪 [Colleen Cutcliffe Style]: ",
  },
  {
    id: "gass",
    name: "Stefanie Gass",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Podcast & Coach Copywriting",
    focus: "Podcasting lead generation & faith-based coaching",
    stylePreset: "The AI Innovator",
    keyConcept: "Use organic podcasting as your primary high-trust funnel.",
    promptPrefix: "🎙️ [Stefanie Gass Style]: ",
  },
  {
    id: "wylie",
    name: "Kimberly Wylie",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Nurture Email Mastery",
    focus: "Relationship-first email sequences",
    stylePreset: "The AI Innovator",
    keyConcept: "Nurture leads like lifelong friends.",
    promptPrefix: "🌿 [Kimberly Wylie Style]: ",
  },
  {
    id: "hussain",
    name: "Delwar Hussain",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Direct Response Email",
    focus: "Affiliate & direct response email blasts",
    stylePreset: "The AI Innovator",
    keyConcept: "Focus on curiosity subject lines and fast single-idea calls to action.",
    promptPrefix: "⚡ [Delwar Hussain Style]: ",
  },
  {
    id: "usborne",
    name: "Nick Usborne",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Conversational Web Copy",
    focus: "Web-native conversational writing",
    stylePreset: "The AI Innovator",
    keyConcept: "Write for the screen the way people read: scanning and conversational.",
    promptPrefix: "🖥️ [Nick Usborne Style]: ",
  },
  {
    id: "mccarthy",
    name: "Ken McCarthy",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "System Seminar Pioneer",
    focus: "Internet direct response foundation",
    stylePreset: "The AI Innovator",
    keyConcept: "Apply classic direct response testing to web traffic.",
    promptPrefix: "🏛️ [Ken McCarthy Style]: ",
  },
  {
    id: "ramsey",
    name: "Dave Ramsey",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Financial Peace",
    focus: "Fear/security driven debt freedom copy",
    stylePreset: "The AI Innovator",
    keyConcept: "Use tough love and hope to inspire life-changing financial action.",
    promptPrefix: "💵 [Dave Ramsey Style]: ",
  },
  {
    id: "axe",
    name: "Dr. Axe",
    archetype: "Modern AI & Niche Innovators",
    sampleVoice: "Natural Health & Food is Medicine",
    focus: "Benefit-driven natural health education",
    stylePreset: "The AI Innovator",
    keyConcept: "Empower people to heal naturally with clear scientific steps.",
    promptPrefix: "🥗 [Dr. Axe Style]: ",
  },
];
