export interface StateFactGroup {
  capital: string;
  motto: string;
  mottoTranslation?: string;
  nickname: string;
  statehood: string;
  statehoodRank?: string;
  bird: string;
  flower: string;
  tree: string;
  song: string;
  insect?: string;
  fish?: string;
  freshwaterFish?: string;
  saltwaterFish?: string;
  mineral?: string;
  gemstone?: string;
  rock?: string;
  soil?: string;
  fruit?: string;
  beverage?: string;
  quarterYear?: string;
  highestPoint?: string;
  lowestPoint?: string;
  elevationMin?: string;
  elevationMax?: string;
  sosUrl?: string;
  taxDeptUrl?: string;
  areaCodesRange?: string;
  zipCodesRange?: string;
  largestCity: string;
  region: string;
  timezone: string;
  landArea: string;
  population: string;
  abbreviation: string;
}

export const US_STATE_FACTS: Record<string, StateFactGroup> = {
  alabama: {
    capital: "Montgomery",
    motto: "We Dare Defend Our Rights",
    nickname: "The Yellowhammer State",
    statehood: "December 14, 1819 (22nd State)",
    bird: "Yellowhammer",
    flower: "Camellia",
    tree: "Longleaf Pine",
    song: "Alabama",
    insect: "Monarch Butterfly",
    fish: "Largemouth Bass",
    mineral: "Hematite",
    beverage: "Water",
    largestCity: "Huntsville",
    region: "Southeast",
    timezone: "Central Time (CST/CDT)",
    landArea: "52,420 sq mi",
    population: "5,074,000+",
    abbreviation: "AL"
  },
  alaska: {
    capital: "Juneau",
    motto: "North to the Future",
    nickname: "The Last Frontier",
    statehood: "January 3, 1959 (49th State)",
    bird: "Willow Ptarmigan",
    flower: "Forget-Me-Not",
    tree: "Sitka Spruce",
    song: "Alaska's Flag",
    insect: "Four-spotted Skimmer Dragonfly",
    fish: "King Salmon",
    mineral: "Gold",
    beverage: "Water",
    largestCity: "Anchorage",
    region: "Pacific Northwest / Arctic",
    timezone: "Alaska Time (AKST/AKDT)",
    landArea: "665,384 sq mi",
    population: "733,000+",
    abbreviation: "AK"
  },
  arizona: {
    capital: "Phoenix",
    motto: "Ditat Deus (God Enriches)",
    nickname: "The Grand Canyon State",
    statehood: "February 14, 1912 (48th State)",
    bird: "Cactus Wren",
    flower: "Saguaro Cactus Blossom",
    tree: "Palo Verde",
    song: "Arizona",
    insect: "Two-tailed Swallowtail",
    fish: "Apache Trout",
    mineral: "Copper",
    beverage: "Lemonade",
    largestCity: "Phoenix",
    region: "Southwest",
    timezone: "Mountain Time (MST - No DST)",
    landArea: "113,990 sq mi",
    population: "7,360,000+",
    abbreviation: "AZ"
  },
  arkansas: {
    capital: "Little Rock",
    motto: "Regnat Populus (The People Rule)",
    nickname: "The Natural State",
    statehood: "June 15, 1836 (25th State)",
    bird: "Mockingbird",
    flower: "Apple Blossom",
    tree: "Pine Tree",
    song: "Arkansas",
    insect: "Honeybee",
    fish: "Alligator Gar",
    mineral: "Quartz Crystal",
    beverage: "Milk",
    largestCity: "Little Rock",
    region: "Southeast",
    timezone: "Central Time (CST/CDT)",
    landArea: "53,179 sq mi",
    population: "3,045,000+",
    abbreviation: "AR"
  },
  california: {
    capital: "Sacramento",
    motto: "Eureka (I Have Found It)",
    nickname: "The Golden State",
    statehood: "September 9, 1850 (31st State)",
    bird: "California Quail",
    flower: "California Poppy",
    tree: "California Redwood",
    song: "I Love You, California",
    insect: "California Dogface Butterfly",
    fish: "Golden Trout",
    mineral: "Gold",
    beverage: "Wine / Almond Milk",
    largestCity: "Los Angeles",
    region: "West Coast",
    timezone: "Pacific Time (PST/PDT)",
    landArea: "163,696 sq mi",
    population: "38,900,000+",
    abbreviation: "CA"
  },
  colorado: {
    capital: "Denver",
    motto: "Nil Sine Numine (Nothing Without Providence)",
    nickname: "The Centennial State",
    statehood: "August 1, 1876 (38th State)",
    bird: "Lark Bunting",
    flower: "Rocky Mountain Columbine",
    tree: "Colorado Blue Spruce",
    song: "Where the Columbines Grow",
    insect: "Colorado Hairstreak Butterfly",
    fish: "Greenback Cutthroat Trout",
    mineral: "Rhodochrosite",
    beverage: "Craft Beer / Water",
    largestCity: "Denver",
    region: "West / Rocky Mountains",
    timezone: "Mountain Time (MST/MDT)",
    landArea: "104,094 sq mi",
    population: "5,840,000+",
    abbreviation: "CO"
  },
  connecticut: {
    capital: "Hartford",
    motto: "Qui Transtulit Sustinet (He Who Transplanted Still Sustains)",
    nickname: "The Constitution State / Nutmeg State",
    statehood: "January 9, 1788 (5th State)",
    bird: "American Robin",
    flower: "Mountain Laurel",
    tree: "Charter Oak",
    song: "Yankee Doodle",
    insect: "European Mantis",
    fish: "American Shad",
    mineral: "Almandine Garnet",
    beverage: "Milk",
    largestCity: "Bridgeport",
    region: "New England / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "5,543 sq mi",
    population: "3,626,000+",
    abbreviation: "CT"
  },
  delaware: {
    capital: "Dover",
    motto: "Liberty and Independence",
    nickname: "The First State / The Diamond State",
    statehood: "December 7, 1787 (1st State)",
    bird: "Blue Hen Chicken",
    flower: "Peach Blossom",
    tree: "American Holly",
    song: "Our Delaware",
    insect: "Ladybug",
    fish: "Weakfish",
    mineral: "Sillimanite",
    beverage: "Milk",
    largestCity: "Wilmington",
    region: "Mid-Atlantic / South Atlantic",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "1,948 sq mi",
    population: "1,030,000+",
    abbreviation: "DE"
  },
  florida: {
    capital: "Tallahassee",
    motto: "In God We Trust",
    nickname: "The Sunshine State",
    statehood: "March 3, 1845 (27th State)",
    bird: "Northern Mockingbird",
    flower: "Orange Blossom",
    tree: "Sabal Palm",
    song: "Old Folks at Home",
    insect: "Zebra Longwing Butterfly",
    fish: "Sailfish / Largemouth Bass",
    mineral: "Agatized Coral",
    beverage: "Orange Juice",
    largestCity: "Jacksonville",
    region: "Southeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "65,757 sq mi",
    population: "22,600,000+",
    abbreviation: "FL"
  },
  georgia: {
    capital: "Atlanta",
    motto: "Wisdom, Justice, and Moderation",
    nickname: "The Peach State / Empire State of the South",
    statehood: "January 2, 1788 (4th State)",
    bird: "Brown Thrasher",
    flower: "Cherokee Rose",
    tree: "Live Oak",
    song: "Georgia on My Mind",
    insect: "Honeybee",
    fish: "Largemouth Bass",
    mineral: "Quartz",
    beverage: "Peach Cider / Sweet Tea",
    largestCity: "Atlanta",
    region: "Southeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "59,425 sq mi",
    population: "11,000,000+",
    abbreviation: "GA"
  },
  hawaii: {
    capital: "Honolulu",
    motto: "Ua Mau ke Ea o ka ʻĀina i ka Pono",
    nickname: "The Aloha State",
    statehood: "August 21, 1959 (50th State)",
    bird: "Nēnē (Hawaiian Goose)",
    flower: "Yellow Hibiscus",
    tree: "Kukui Tree (Candlenut)",
    song: "Hawaiʻi Ponoʻī",
    insect: "Kamehameha Butterfly",
    fish: "Humuhumunukunukuāpuaʻa",
    mineral: "Black Coral",
    beverage: "Fruit Juice / Water",
    largestCity: "Honolulu",
    region: "Pacific Islands",
    timezone: "Hawaii Standard Time (HST - No DST)",
    landArea: "10,931 sq mi",
    population: "1,440,000+",
    abbreviation: "HI"
  },
  idaho: {
    capital: "Boise",
    motto: "Esto Perpetua (Let It Be Perpetual)",
    nickname: "The Gem State",
    statehood: "July 3, 1890 (43rd State)",
    bird: "Mountain Bluebird",
    flower: "Syringa",
    tree: "Western White Pine",
    song: "Here We Have Idaho",
    insect: "Monarch Butterfly",
    fish: "Cutthroat Trout",
    mineral: "Star Garnet",
    beverage: "Milk",
    largestCity: "Boise",
    region: "Pacific Northwest / Intermountain West",
    timezone: "Mountain Time (MST/MDT)",
    landArea: "83,569 sq mi",
    population: "1,960,000+",
    abbreviation: "ID"
  },
  illinois: {
    capital: "Springfield",
    motto: "State Sovereignty, National Union",
    nickname: "Land of Lincoln / Prairie State",
    statehood: "December 3, 1818 (21st State)",
    bird: "Northern Cardinal",
    flower: "Violet",
    tree: "White Oak",
    song: "Illinois",
    insect: "Monarch Butterfly",
    fish: "Bluegill",
    mineral: "Fluorite",
    beverage: "Milk",
    largestCity: "Chicago",
    region: "Midwest",
    timezone: "Central Time (CST/CDT)",
    landArea: "57,915 sq mi",
    population: "12,580,000+",
    abbreviation: "IL"
  },
  indiana: {
    capital: "Indianapolis",
    motto: "The Crossroads of America",
    nickname: "The Hoosier State",
    statehood: "December 11, 1816 (19th State)",
    bird: "Northern Cardinal",
    flower: "Peony",
    tree: "Tulip Tree",
    song: "On the Banks of the Wabash, Far Away",
    insect: "Say's Firefly",
    fish: "Largemouth Bass",
    mineral: "Salem Limestone",
    beverage: "Water",
    largestCity: "Indianapolis",
    region: "Midwest",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "36,419 sq mi",
    population: "6,830,000+",
    abbreviation: "IN"
  },
  iowa: {
    capital: "Des Moines",
    motto: "Our Liberties We Prize and Our Rights We Will Maintain",
    nickname: "The Hawkeye State",
    statehood: "December 28, 1846 (29th State)",
    bird: "Eastern Goldfinch",
    flower: "Wild Prairie Rose",
    tree: "Bur Oak",
    song: "The Song of Iowa",
    insect: "Honeybee",
    fish: "Channel Catfish",
    mineral: "Geode",
    beverage: "Milk",
    largestCity: "Des Moines",
    region: "Midwest",
    timezone: "Central Time (CST/CDT)",
    landArea: "56,273 sq mi",
    population: "3,200,000+",
    abbreviation: "IA"
  },
  kansas: {
    capital: "Topeka",
    motto: "Ad Astra per Aspera (To the Stars Through Difficulties)",
    nickname: "The Sunflower State",
    statehood: "January 29, 1861 (34th State)",
    bird: "Western Meadowlark",
    flower: "Wild Native Sunflower",
    tree: "Cottonwood",
    song: "Home on the Range",
    insect: "Honeybee",
    fish: "Channel Catfish",
    mineral: "Galena",
    beverage: "Milk",
    largestCity: "Wichita",
    region: "Midwest / Great Plains",
    timezone: "Central Time (CST/CDT)",
    landArea: "82,278 sq mi",
    population: "2,940,000+",
    abbreviation: "KS"
  },
  kentucky: {
    capital: "Frankfort",
    motto: "United We Stand, Divided We Fall",
    nickname: "The Bluegrass State",
    statehood: "June 1, 1792 (15th State)",
    bird: "Northern Cardinal",
    flower: "Goldenrod",
    tree: "Tulip Poplar",
    song: "My Old Kentucky Home",
    insect: "Honeybee",
    fish: "Kentucky Spotted Bass",
    mineral: "Coal / Freshwater Pearl",
    beverage: "Milk / Bourbon",
    largestCity: "Louisville",
    region: "Southeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "40,408 sq mi",
    population: "4,520,000+",
    abbreviation: "KY"
  },
  louisiana: {
    capital: "Baton Rouge",
    motto: "Union, Justice, Confidence",
    nickname: "The Pelican State",
    statehood: "April 30, 1812 (18th State)",
    bird: "Brown Pelican",
    flower: "Magnolia",
    tree: "Bald Cypress",
    song: "You Are My Sunshine",
    insect: "Honeybee",
    fish: "White Crappie",
    mineral: "Agate",
    beverage: "Milk",
    largestCity: "New Orleans",
    region: "Southeast / Gulf Coast",
    timezone: "Central Time (CST/CDT)",
    landArea: "52,378 sq mi",
    population: "4,590,000+",
    abbreviation: "LA"
  },
  maine: {
    capital: "Augusta",
    motto: "Dirigo (I Lead)",
    nickname: "The Pine Tree State",
    statehood: "March 15, 1820 (23rd State)",
    bird: "Black-capped Chickadee",
    flower: "White Pine Cone and Tassel",
    tree: "Eastern White Pine",
    song: "State of Maine Song",
    insect: "Honeybee",
    fish: "Landlocked Salmon",
    mineral: "Tourmaline",
    beverage: "Moxie / Milk",
    largestCity: "Portland",
    region: "New England / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "35,385 sq mi",
    population: "1,390,000+",
    abbreviation: "ME"
  },
  maryland: {
    capital: "Annapolis",
    motto: "Fatti Maschii, Parole Femine (Manly Deeds, Womanly Words)",
    nickname: "The Old Line State / Free State",
    statehood: "April 28, 1788 (7th State)",
    bird: "Baltimore Oriole",
    flower: "Black-Eyed Susan",
    tree: "White Oak",
    song: "Maryland, My Maryland",
    insect: "Checkerspot Butterfly",
    fish: "Rockfish (Striped Bass)",
    mineral: "Patuxent River Stone",
    beverage: "Milk",
    largestCity: "Baltimore",
    region: "Mid-Atlantic",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "12,407 sq mi",
    population: "6,180,000+",
    abbreviation: "MD"
  },
  massachusetts: {
    capital: "Boston",
    motto: "Ense Petit Placidam Sub Libertate Quietem",
    nickname: "The Bay State / Old Colony State",
    statehood: "February 6, 1788 (6th State)",
    bird: "Black-capped Chickadee",
    flower: "Mayflower",
    tree: "American Elm",
    song: "All Hail to Massachusetts",
    insect: "7-spot Ladybug",
    fish: "Cod",
    mineral: "Babingtonite",
    beverage: "Cranberry Juice",
    largestCity: "Boston",
    region: "New England / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "10,554 sq mi",
    population: "7,000,000+",
    abbreviation: "MA"
  },
  michigan: {
    capital: "Lansing",
    motto: "Si Quaeris Peninsulam Amoenam Circumspice",
    nickname: "The Great Lakes State / Wolverine State",
    statehood: "January 26, 1837 (26th State)",
    bird: "American Robin",
    flower: "Apple Blossom",
    tree: "Eastern White Pine",
    song: "Michigan, My Michigan",
    insect: "Green Darner Dragonfly",
    fish: "Brook Trout",
    mineral: "Petoskey Stone",
    beverage: "Milk",
    largestCity: "Detroit",
    region: "Midwest / Great Lakes",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "96,716 sq mi",
    population: "10,030,000+",
    abbreviation: "MI"
  },
  minnesota: {
    capital: "St. Paul",
    motto: "L'Étoile du Nord (Star of the North)",
    nickname: "The North Star State / Land of 10,000 Lakes",
    statehood: "May 11, 1858 (32nd State)",
    bird: "Common Loon",
    flower: "Pink and White Lady's Slipper",
    tree: "Red Pine",
    song: "Hail! Minnesota",
    insect: "Rusty Patched Bumble Bee",
    fish: "Walleye",
    mineral: "Lake Superior Agate",
    beverage: "Milk",
    largestCity: "Minneapolis",
    region: "Midwest",
    timezone: "Central Time (CST/CDT)",
    landArea: "86,936 sq mi",
    population: "5,720,000+",
    abbreviation: "MN"
  },
  mississippi: {
    capital: "Jackson",
    motto: "Virtute et Armis (By Valor and Arms)",
    nickname: "The Magnolia State",
    statehood: "December 10, 1817 (20th State)",
    bird: "Northern Mockingbird",
    flower: "Magnolia",
    tree: "Magnolia",
    song: "Go, Mississippi",
    insect: "Honeybee",
    fish: "Largemouth Bass",
    mineral: "Petrified Wood",
    beverage: "Milk",
    largestCity: "Jackson",
    region: "Southeast",
    timezone: "Central Time (CST/CDT)",
    landArea: "48,432 sq mi",
    population: "2,940,000+",
    abbreviation: "MS"
  },
  missouri: {
    capital: "Jefferson City",
    motto: "Salus Populi Suprema Lex Esto",
    nickname: "The Show-Me State",
    statehood: "August 10, 1821 (24th State)",
    bird: "Eastern Bluebird",
    flower: "Hawthorn",
    tree: "Flowering Dogwood",
    song: "Missouri Waltz",
    insect: "Honeybee",
    fish: "Channel Catfish",
    mineral: "Galena",
    beverage: "Milk",
    largestCity: "Kansas City",
    region: "Midwest",
    timezone: "Central Time (CST/CDT)",
    landArea: "69,707 sq mi",
    population: "6,180,000+",
    abbreviation: "MO"
  },
  montana: {
    capital: "Helena",
    motto: "Oro y Plata (Gold and Silver)",
    nickname: "The Treasure State / Big Sky Country",
    statehood: "November 8, 1889 (41st State)",
    bird: "Western Meadowlark",
    flower: "Bitterroot",
    tree: "Ponderosa Pine",
    song: "Montana",
    insect: "Mourning Cloak Butterfly",
    fish: "Blackspotted Cutthroat Trout",
    mineral: "Sapphire / Agate",
    beverage: "Milk",
    largestCity: "Billings",
    region: "Mountain West",
    timezone: "Mountain Time (MST/MDT)",
    landArea: "147,040 sq mi",
    population: "1,130,000+",
    abbreviation: "MT"
  },
  nebraska: {
    capital: "Lincoln",
    motto: "Equality Before the Law",
    nickname: "The Cornhusker State",
    statehood: "March 1, 1867 (37th State)",
    bird: "Western Meadowlark",
    flower: "Goldenrod",
    tree: "Cottonwood",
    song: "Beautiful Nebraska",
    insect: "Honeybee",
    fish: "Channel Catfish",
    mineral: "Prairie Agate",
    beverage: "Milk",
    largestCity: "Omaha",
    region: "Midwest / Great Plains",
    timezone: "Central Time (CST/CDT)",
    landArea: "77,358 sq mi",
    population: "1,970,000+",
    abbreviation: "NE"
  },
  nevada: {
    capital: "Carson City",
    motto: "All For Our Country",
    nickname: "The Silver State / Battle Born State",
    statehood: "October 31, 1864 (36th State)",
    bird: "Mountain Bluebird",
    flower: "Sagebrush",
    tree: "Single-Leaf Pinyon",
    song: "Home Means Nevada",
    insect: "Viceroy Butterfly",
    fish: "Lahontan Cutthroat Trout",
    mineral: "Silver",
    beverage: "Water",
    largestCity: "Las Vegas",
    region: "West / Intermountain",
    timezone: "Pacific Time (PST/PDT)",
    landArea: "110,572 sq mi",
    population: "3,190,000+",
    abbreviation: "NV"
  },
  newhampshire: {
    capital: "Concord",
    motto: "Live Free or Die",
    nickname: "The Granite State",
    statehood: "June 21, 1788 (9th State)",
    bird: "Purple Finch",
    flower: "Purple Lilac",
    tree: "White Birch",
    song: "Old New Hampshire",
    insect: "Ladybug",
    fish: "Brook Trout",
    mineral: "Smoky Quartz",
    beverage: "Apple Cider",
    largestCity: "Manchester",
    region: "New England / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "9,349 sq mi",
    population: "1,400,000+",
    abbreviation: "NH"
  },
  newjersey: {
    capital: "Trenton",
    motto: "Liberty and Prosperity",
    nickname: "The Garden State",
    statehood: "December 18, 1787 (3rd State)",
    bird: "Eastern Goldfinch",
    flower: "Violet",
    tree: "Red Oak",
    song: "I'm From New Jersey",
    insect: "Honeybee",
    fish: "Brook Trout",
    mineral: "Franklinite",
    beverage: "Milk",
    largestCity: "Newark",
    region: "Mid-Atlantic / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "8,723 sq mi",
    population: "9,290,000+",
    abbreviation: "NJ"
  },
  newmexico: {
    capital: "Santa Fe",
    motto: "Crescit Eundo (It Grows as It Goes)",
    nickname: "Land of Enchantment",
    statehood: "January 6, 1912 (47th State)",
    bird: "Greater Roadrunner",
    flower: "Yucca Flower",
    tree: "Two-Needle Pinyon",
    song: "O Fair New Mexico",
    insect: "Tarantula Hawk Wasp",
    fish: "Rio Grande Cutthroat Trout",
    mineral: "Turquoise",
    beverage: "Milk",
    largestCity: "Albuquerque",
    region: "Southwest",
    timezone: "Mountain Time (MST/MDT)",
    landArea: "121,590 sq mi",
    population: "2,115,000+",
    abbreviation: "NM"
  },
  newyork: {
    capital: "Albany",
    motto: "Excelsior (Ever Upward)",
    nickname: "The Empire State",
    statehood: "July 26, 1788 (11th State)",
    bird: "Eastern Bluebird",
    flower: "Rose",
    tree: "Sugar Maple",
    song: "I Love New York",
    insect: "9-spotted Ladybug",
    fish: "Brook Trout",
    mineral: "Herkimer Diamond",
    beverage: "Milk",
    largestCity: "New York City",
    region: "Mid-Atlantic / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "54,555 sq mi",
    population: "19,570,000+",
    abbreviation: "NY"
  },
  northcarolina: {
    capital: "Raleigh",
    motto: "Esse Quam Videri (To Be, Rather Than to Seem)",
    nickname: "The Tar Heel State / Old North State",
    statehood: "November 21, 1789 (12th State)",
    bird: "Northern Cardinal",
    flower: "Flowering Dogwood",
    tree: "Longleaf Pine",
    song: "The Old North State",
    insect: "Honeybee",
    fish: "Channel Bass (Red Drum)",
    mineral: "Emerald",
    beverage: "Milk / Scuppernong Wine",
    largestCity: "Charlotte",
    region: "Southeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "53,819 sq mi",
    population: "10,700,000+",
    abbreviation: "NC"
  },
  northdakota: {
    capital: "Bismarck",
    motto: "Liberty and Union, Now and Forever, One and Inseparable",
    nickname: "The Peace Garden State / Roughrider State",
    statehood: "November 2, 1889 (39th State)",
    bird: "Western Meadowlark",
    flower: "Wild Prairie Rose",
    tree: "American Elm",
    song: "North Dakota Hymn",
    insect: "Convergent Lady Beetle",
    fish: "Northern Pike",
    mineral: "Teredo Petrified Wood",
    beverage: "Milk",
    largestCity: "Fargo",
    region: "Midwest / Great Plains",
    timezone: "Central Time (CST/CDT)",
    landArea: "70,698 sq mi",
    population: "780,000+",
    abbreviation: "ND"
  },
  ohio: {
    capital: "Columbus",
    motto: "With God, All Things Are Possible",
    nickname: "The Buckeye State",
    statehood: "March 1, 1803 (17th State)",
    bird: "Northern Cardinal",
    flower: "Scarlet Carnation",
    tree: "Ohio Buckeye",
    song: "Beautiful Ohio",
    insect: "Ladybug",
    fish: "Walleye",
    mineral: "Flint",
    beverage: "Tomato Juice",
    largestCity: "Columbus",
    region: "Midwest",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "44,825 sq mi",
    population: "11,780,000+",
    abbreviation: "OH"
  },
  oklahoma: {
    capital: "Oklahoma City",
    motto: "Labor Omnia Vincit (Labor Conquers All Things)",
    nickname: "The Sooner State",
    statehood: "November 16, 1907 (46th State)",
    bird: "Scissor-tailed Flycatcher",
    flower: "Oklahoma Rose",
    tree: "Redbud",
    song: "Oklahoma!",
    insect: "Honeybee",
    fish: "White Bass",
    mineral: "Barite Rose",
    beverage: "Milk",
    largestCity: "Oklahoma City",
    region: "South / Great Plains",
    timezone: "Central Time (CST/CDT)",
    landArea: "69,899 sq mi",
    population: "4,020,000+",
    abbreviation: "OK"
  },
  oregon: {
    capital: "Salem",
    motto: "Alis Volat Propriis (She Flies With Her Own Wings)",
    nickname: "The Beaver State",
    statehood: "February 14, 1859 (33rd State)",
    bird: "Western Meadowlark",
    flower: "Oregon Grape",
    tree: "Douglas Fir",
    song: "Oregon, My Oregon",
    insect: "Oregon Swallowtail Butterfly",
    fish: "Chinook Salmon",
    mineral: "Oregon Sunstone",
    beverage: "Milk",
    largestCity: "Portland",
    region: "Pacific Northwest",
    timezone: "Pacific Time (PST/PDT)",
    landArea: "98,378 sq mi",
    population: "4,240,000+",
    abbreviation: "OR"
  },
  pennsylvania: {
    capital: "Harrisburg",
    motto: "Virtue, Liberty, and Independence",
    nickname: "The Keystone State",
    statehood: "December 12, 1787 (2nd State)",
    bird: "Ruffed Grouse",
    flower: "Mountain Laurel",
    tree: "Eastern Hemlock",
    song: "Pennsylvania",
    insect: "Firefly",
    fish: "Brook Trout",
    mineral: "Celestite",
    beverage: "Milk",
    largestCity: "Philadelphia",
    region: "Mid-Atlantic / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "46,054 sq mi",
    population: "12,960,000+",
    abbreviation: "PA"
  },
  rhodeisland: {
    capital: "Providence",
    motto: "Hope",
    nickname: "The Ocean State",
    statehood: "May 29, 1790 (13th State)",
    bird: "Rhode Island Red",
    flower: "Violet",
    tree: "Red Maple",
    song: "Rhode Island's It for Me",
    insect: "American Burying Beetle",
    fish: "Striped Bass",
    mineral: "Cumberlandite",
    beverage: "Coffee Milk",
    largestCity: "Providence",
    region: "New England / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "1,214 sq mi",
    population: "1,090,000+",
    abbreviation: "RI"
  },
  southcarolina: {
    capital: "Columbia",
    motto: "Dum Spiro Spero (While I Breathe, I Hope)",
    nickname: "The Palmetto State",
    statehood: "May 23, 1788 (8th State)",
    bird: "Carolina Wren",
    flower: "Yellow Jessamine",
    tree: "Sabal Palmetto",
    song: "Carolina",
    insect: "Carolina Mantis",
    fish: "Striped Bass",
    mineral: "Amethyst",
    beverage: "Milk / Sweet Tea",
    largestCity: "Charleston",
    region: "Southeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "32,020 sq mi",
    population: "5,370,000+",
    abbreviation: "SC"
  },
  southdakota: {
    capital: "Pierre",
    motto: "Under God the People Rule",
    nickname: "The Mount Rushmore State",
    statehood: "November 2, 1889 (40th State)",
    bird: "Ring-necked Pheasant",
    flower: "Pasque Flower",
    tree: "Black Hills Spruce",
    song: "Hail, South Dakota",
    insect: "Honeybee",
    fish: "Walleye",
    mineral: "Fairburn Agate",
    beverage: "Milk",
    largestCity: "Sioux Falls",
    region: "Midwest / Great Plains",
    timezone: "Central Time (CST/CDT)",
    landArea: "77,116 sq mi",
    population: "915,000+",
    abbreviation: "SD"
  },
  tennessee: {
    capital: "Nashville",
    motto: "Agriculture and Commerce",
    nickname: "The Volunteer State",
    statehood: "June 1, 1796 (16th State)",
    bird: "Northern Mockingbird",
    flower: "Iris",
    tree: "Tulip Poplar",
    song: "Rocky Top / Tennessee Waltz",
    insect: "Firefly / Honeybee",
    fish: "Smallmouth Bass",
    mineral: "Agate",
    beverage: "Milk",
    largestCity: "Nashville",
    region: "Southeast",
    timezone: "Central Time (CST/CDT)",
    landArea: "42,144 sq mi",
    population: "7,050,000+",
    abbreviation: "TN"
  },
  texas: {
    capital: "Austin",
    motto: "Friendship",
    nickname: "The Lone Star State",
    statehood: "December 29, 1845 (28th State)",
    bird: "Northern Mockingbird",
    flower: "Bluebonnet",
    tree: "Pecan",
    song: "Texas, Our Texas",
    insect: "Monarch Butterfly",
    fish: "Guadalupe Bass",
    mineral: "Texas Blue Topaz",
    beverage: "Dr Pepper / Sweet Tea",
    largestCity: "Houston",
    region: "South / Southwest",
    timezone: "Central Time (CST/CDT)",
    landArea: "268,596 sq mi",
    population: "30,500,000+",
    abbreviation: "TX"
  },
  utah: {
    capital: "Salt Lake City",
    motto: "Industry",
    nickname: "The Beehive State",
    statehood: "January 4, 1896 (45th State)",
    bird: "California Gull",
    flower: "Sego Lily",
    tree: "Quaking Aspen",
    song: "Utah, This Is the Place",
    insect: "Honeybee",
    fish: "Bonneville Cutthroat Trout",
    mineral: "Topaz",
    beverage: "Milk",
    largestCity: "Salt Lake City",
    region: "Mountain West",
    timezone: "Mountain Time (MST/MDT)",
    landArea: "84,897 sq mi",
    population: "3,380,000+",
    abbreviation: "UT"
  },
  vermont: {
    capital: "Montpelier",
    motto: "Freedom and Unity",
    nickname: "The Green Mountain State",
    statehood: "March 4, 1791 (14th State)",
    bird: "Hermit Thrush",
    flower: "Red Clover",
    tree: "Sugar Maple",
    song: "These Green Mountains",
    insect: "Honeybee",
    fish: "Brook Trout",
    mineral: "Grossular Garnet",
    beverage: "Milk / Maple Syrup",
    largestCity: "Burlington",
    region: "New England / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "9,616 sq mi",
    population: "647,000+",
    abbreviation: "VT"
  },
  virginia: {
    capital: "Richmond",
    motto: "Sic Semper Tyrannis (Thus Always to Tyrants)",
    nickname: "The Old Dominion / Mother of Presidents",
    statehood: "June 25, 1788 (10th State)",
    bird: "Northern Cardinal",
    flower: "American Dogwood",
    tree: "American Dogwood",
    song: "Carry Me Back to Old Virginny",
    insect: "Tiger Swallowtail Butterfly",
    fish: "Brook Trout",
    mineral: "Nelsonite",
    beverage: "Milk",
    largestCity: "Virginia Beach",
    region: "Southeast / Mid-Atlantic",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "42,775 sq mi",
    population: "8,680,000+",
    abbreviation: "VA"
  },
  washington: {
    capital: "Olympia",
    motto: "Al-ki (By and By)",
    nickname: "The Evergreen State",
    statehood: "November 11, 1889 (42nd State)",
    bird: "American Goldfinch",
    flower: "Coast Rhododendron",
    tree: "Western Hemlock",
    song: "Washington, My Home",
    insect: "Green Darner Dragonfly",
    fish: "Steelhead Trout",
    mineral: "Petrified Wood",
    beverage: "Milk / Coffee",
    largestCity: "Seattle",
    region: "Pacific Northwest",
    timezone: "Pacific Time (PST/PDT)",
    landArea: "71,298 sq mi",
    population: "7,780,000+",
    abbreviation: "WA"
  },
  westvirginia: {
    capital: "Charleston",
    motto: "Montani Semper Liberi (Mountaineers Are Always Free)",
    nickname: "The Mountain State",
    statehood: "June 20, 1863 (35th State)",
    bird: "Northern Cardinal",
    flower: "Rhododendron",
    tree: "Sugar Maple",
    song: "Take Me Home, Country Roads",
    insect: "Honeybee",
    fish: "Brook Trout",
    mineral: "Lithostrotionella Fossil Coral",
    beverage: "Milk",
    largestCity: "Charleston",
    region: "Appalachia / Mid-Atlantic",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "24,230 sq mi",
    population: "1,775,000+",
    abbreviation: "WV"
  },
  wisconsin: {
    capital: "Madison",
    motto: "Forward",
    nickname: "The Badger State",
    statehood: "May 29, 1848 (30th State)",
    bird: "American Robin",
    flower: "Wood Violet",
    tree: "Sugar Maple",
    song: "On, Wisconsin!",
    insect: "Honeybee",
    fish: "Muskellunge (Muskie)",
    mineral: "Galena",
    beverage: "Milk",
    largestCity: "Milwaukee",
    region: "Midwest",
    timezone: "Central Time (CST/CDT)",
    landArea: "65,496 sq mi",
    population: "5,890,000+",
    abbreviation: "WI"
  },
  wyoming: {
    capital: "Cheyenne",
    motto: "Equal Rights",
    nickname: "The Equality State / Cowboy State",
    statehood: "July 10, 1890 (44th State)",
    bird: "Western Meadowlark",
    flower: "Indian Paintbrush",
    tree: "Plains Cottonwood",
    song: "Wyoming",
    insect: "Sheridan's Green Hairstreak Butterfly",
    fish: "Cutthroat Trout",
    mineral: "Jade",
    beverage: "Milk",
    largestCity: "Cheyenne",
    region: "Mountain West",
    timezone: "Mountain Time (MST/MDT)",
    landArea: "97,813 sq mi",
    population: "580,000+",
    abbreviation: "WY"
  }
};

export function getStateFacts(stateSlugOrName: string): StateFactGroup {
  const normalized = (stateSlugOrName || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z]/g, '');

  if (US_STATE_FACTS[normalized]) {
    return US_STATE_FACTS[normalized];
  }

  // Check matched abbreviation key (e.g., "SC" or "sc")
  const matchedKey = Object.keys(US_STATE_FACTS).find(
    key => US_STATE_FACTS[key].abbreviation.toLowerCase() === normalized
  );
  if (matchedKey) {
    return US_STATE_FACTS[matchedKey];
  }

  // Fallback default for edge cases
  const nameClean = stateSlugOrName ? stateSlugOrName.charAt(0).toUpperCase() + stateSlugOrName.slice(1) : "State";
  return {
    capital: `${nameClean} Capital City`,
    motto: `Liberty & Progress in ${nameClean}`,
    nickname: `The Official ${nameClean} State`,
    statehood: "Established State",
    bird: `${nameClean} Native Songbird`,
    flower: `${nameClean} State Blossom`,
    tree: `${nameClean} Native Heritage Tree`,
    song: `Official Song of ${nameClean}`,
    insect: "Honeybee",
    fish: "Native Freshwater Bass",
    mineral: "State Heritage Gemstone",
    beverage: "Milk",
    largestCity: `${nameClean} Metropolitan Center`,
    region: "United States Region",
    timezone: "Standard US Timezone",
    landArea: "Established State Territory",
    population: "State Population Registry",
    abbreviation: nameClean.slice(0, 2).toUpperCase()
  };
}
