export interface StateFactGroup {
  capital: string;
  motto: string;
  mottoTranslation?: string;
  nickname: string;
  statehood: string;
  statehoodRank?: string;
  bird: string;
  flower: string;
  tree: string;
  song: string;
  insect?: string;
  fish?: string;
  freshwaterFish?: string;
  saltwaterFish?: string;
  mineral?: string;
  gemstone?: string;
  rock?: string;
  soil?: string;
  fruit?: string;
  beverage?: string;
  quarterYear?: string;
  highestPoint?: string;
  lowestPoint?: string;
  elevationMin?: string;
  elevationMax?: string;
  stateWebsite?: string;
  sosUrl?: string;
  taxDeptUrl?: string;
  areaCodesRange?: string;
  zipCodesRange?: string;
  largestCity: string;
  region: string;
  timezone: string;
  landArea: string;
  population: string;
  abbreviation: string;
}

export const US_STATE_FACTS: Record<string, StateFactGroup> = {
  alabama: {
    capital: "Montgomery",
    motto: "Audemus Jura Nostra Defendere",
    mottoTranslation: "We Dare Defend Our Rights",
    nickname: "The Yellowhammer State",
    statehood: "December 14, 1819",
    statehoodRank: "22nd State",
    bird: "Yellowhammer",
    flower: "Camellia",
    tree: "Longleaf Pine",
    song: "Alabama",
    insect: "Monarch Butterfly",
    fish: "Largemouth Bass",
    freshwaterFish: "Largemouth Bass",
    saltwaterFish: "Tarpon",
    mineral: "Hematite",
    gemstone: "Star Blue Quartz",
    rock: "Marble",
    beverage: "Water",
    quarterYear: "2003",
    highestPoint: "Cheaha Mountain: 2,413 ft (735 m)",
    lowestPoint: "Gulf of Mexico: 0 ft (0 m)",
    stateWebsite: "https://www.alabama.gov",
    sosUrl: "https://www.sos.alabama.gov",
    taxDeptUrl: "https://revenue.alabama.gov",
    areaCodesRange: "205, 251, 256, 334, 938",
    zipCodesRange: "35004 – 36925",
    largestCity: "Huntsville",
    region: "Southeast",
    timezone: "Central Time (CST/CDT)",
    landArea: "52,420 sq mi",
    population: "5,074,000+",
    abbreviation: "AL"
  },
  alaska: {
    capital: "Juneau",
    motto: "North to the Future",
    mottoTranslation: "Looking Ahead to Tomorrow",
    nickname: "The Last Frontier",
    statehood: "January 3, 1959",
    statehoodRank: "49th State",
    bird: "Willow Ptarmigan",
    flower: "Forget-Me-Not",
    tree: "Sitka Spruce",
    song: "Alaska's Flag",
    insect: "Four-spotted Skimmer Dragonfly",
    fish: "King Salmon",
    freshwaterFish: "King Salmon",
    mineral: "Gold",
    gemstone: "Nephrite Jade",
    beverage: "Water",
    quarterYear: "2008",
    highestPoint: "Denali: 20,310 ft (6,190 m)",
    lowestPoint: "Pacific Ocean: 0 ft (0 m)",
    stateWebsite: "https://alaska.gov",
    sosUrl: "https://www.commerce.alaska.gov/web/cbpl",
    taxDeptUrl: "https://tax.alaska.gov",
    areaCodesRange: "907",
    zipCodesRange: "99501 – 99950",
    largestCity: "Anchorage",
    region: "Pacific Northwest / Arctic",
    timezone: "Alaska Time (AKST/AKDT)",
    landArea: "665,384 sq mi",
    population: "733,000+",
    abbreviation: "AK"
  },
  arizona: {
    capital: "Phoenix",
    motto: "Ditat Deus",
    mottoTranslation: "God Enriches",
    nickname: "The Grand Canyon State",
    statehood: "February 14, 1912",
    statehoodRank: "48th State",
    bird: "Cactus Wren",
    flower: "Saguaro Cactus Blossom",
    tree: "Palo Verde",
    song: "Arizona",
    insect: "Two-tailed Swallowtail",
    fish: "Apache Trout",
    mineral: "Copper",
    gemstone: "Turquoise",
    beverage: "Lemonade",
    quarterYear: "2008",
    highestPoint: "Humphreys Peak: 12,637 ft (3,852 m)",
    lowestPoint: "Colorado River: 70 ft (21 m)",
    stateWebsite: "https://az.gov",
    sosUrl: "https://azsos.gov",
    taxDeptUrl: "https://azdor.gov",
    areaCodesRange: "480, 520, 602, 623, 928",
    zipCodesRange: "85001 – 86556",
    largestCity: "Phoenix",
    region: "Southwest",
    timezone: "Mountain Time (MST - No DST)",
    landArea: "113,990 sq mi",
    population: "7,360,000+",
    abbreviation: "AZ"
  },
  arkansas: {
    capital: "Little Rock",
    motto: "Regnat Populus",
    mottoTranslation: "The People Rule",
    nickname: "The Natural State",
    statehood: "June 15, 1836",
    statehoodRank: "25th State",
    bird: "Mockingbird",
    flower: "Apple Blossom",
    tree: "Pine Tree",
    song: "Arkansas",
    insect: "Honeybee",
    fish: "Alligator Gar",
    mineral: "Quartz Crystal",
    gemstone: "Diamond",
    beverage: "Milk",
    quarterYear: "2003",
    highestPoint: "Mount Magazine: 2,753 ft (839 m)",
    lowestPoint: "Ouachita River: 55 ft (17 m)",
    stateWebsite: "https://portal.arkansas.gov",
    sosUrl: "https://www.sos.arkansas.gov",
    taxDeptUrl: "https://www.dfa.arkansas.gov",
    areaCodesRange: "327, 479, 501, 870",
    zipCodesRange: "71601 – 72959",
    largestCity: "Little Rock",
    region: "Southeast",
    timezone: "Central Time (CST/CDT)",
    landArea: "53,179 sq mi",
    population: "3,045,000+",
    abbreviation: "AR"
  },
  california: {
    capital: "Sacramento",
    motto: "Eureka",
    mottoTranslation: "I Have Found It",
    nickname: "The Golden State",
    statehood: "September 9, 1850",
    statehoodRank: "31st State",
    bird: "California Quail",
    flower: "California Poppy",
    tree: "California Redwood",
    song: "I Love You, California",
    insect: "California Dogface Butterfly",
    fish: "Golden Trout",
    freshwaterFish: "Golden Trout",
    saltwaterFish: "Garibaldi",
    mineral: "Gold",
    gemstone: "Benitoite",
    beverage: "Wine / Milk",
    quarterYear: "2005",
    highestPoint: "Mount Whitney: 14,505 ft (4,421 m)",
    lowestPoint: "Death Valley: -282 ft (-86 m)",
    stateWebsite: "https://www.ca.gov",
    sosUrl: "https://www.sos.ca.gov",
    taxDeptUrl: "https://www.cdtfa.ca.gov",
    areaCodesRange: "209, 213, 310, 408, 415, 510, 619, 714, 818, 916...",
    zipCodesRange: "90001 – 96162",
    largestCity: "Los Angeles",
    region: "West Coast",
    timezone: "Pacific Time (PST/PDT)",
    landArea: "163,696 sq mi",
    population: "38,900,000+",
    abbreviation: "CA"
  },
  colorado: {
    capital: "Denver",
    motto: "Nil Sine Numine",
    mottoTranslation: "Nothing Without Providence",
    nickname: "The Centennial State",
    statehood: "August 1, 1876",
    statehoodRank: "38th State",
    bird: "Lark Bunting",
    flower: "Rocky Mountain Columbine",
    tree: "Colorado Blue Spruce",
    song: "Where the Columbines Grow",
    insect: "Colorado Hairstreak Butterfly",
    fish: "Greenback Cutthroat Trout",
    mineral: "Rhodochrosite",
    gemstone: "Aquamarine",
    beverage: "Craft Beer / Water",
    quarterYear: "2006",
    highestPoint: "Mount Elbert: 14,440 ft (4,401 m)",
    lowestPoint: "Arikaree River: 3,317 ft (1,011 m)",
    stateWebsite: "https://colorado.gov",
    sosUrl: "https://www.sos.state.co.us",
    taxDeptUrl: "https://tax.colorado.gov",
    areaCodesRange: "303, 719, 720, 970",
    zipCodesRange: "80001 – 81658",
    largestCity: "Denver",
    region: "West / Rocky Mountains",
    timezone: "Mountain Time (MST/MDT)",
    landArea: "104,094 sq mi",
    population: "5,840,000+",
    abbreviation: "CO"
  },
  connecticut: {
    capital: "Hartford",
    motto: "Qui Transtulit Sustinet",
    mottoTranslation: "He Who Transplanted Still Sustains",
    nickname: "The Constitution State",
    statehood: "January 9, 1788",
    statehoodRank: "5th State",
    bird: "American Robin",
    flower: "Mountain Laurel",
    tree: "Charter Oak",
    song: "Yankee Doodle",
    insect: "European Mantis",
    fish: "American Shad",
    mineral: "Almandine Garnet",
    gemstone: "Almandine Garnet",
    beverage: "Milk",
    quarterYear: "1999",
    highestPoint: "Mount Frissell: 2,380 ft (725 m)",
    lowestPoint: "Long Island Sound: 0 ft (0 m)",
    stateWebsite: "https://portal.ct.gov",
    sosUrl: "https://portal.ct.gov/sots",
    taxDeptUrl: "https://portal.ct.gov/drs",
    areaCodesRange: "203, 475, 860, 959",
    zipCodesRange: "06001 – 06928",
    largestCity: "Bridgeport",
    region: "New England / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "5,543 sq mi",
    population: "3,626,000+",
    abbreviation: "CT"
  },
  delaware: {
    capital: "Dover",
    motto: "Liberty and Independence",
    mottoTranslation: "Freedom & Autonomy",
    nickname: "The First State",
    statehood: "December 7, 1787",
    statehoodRank: "1st State",
    bird: "Blue Hen Chicken",
    flower: "Peach Blossom",
    tree: "American Holly",
    song: "Our Delaware",
    insect: "Ladybug",
    fish: "Weakfish",
    mineral: "Sillimanite",
    gemstone: "Sillimanite",
    beverage: "Milk",
    quarterYear: "1999",
    highestPoint: "Ebright Azimuth: 448 ft (137 m)",
    lowestPoint: "Atlantic Ocean: 0 ft (0 m)",
    stateWebsite: "https://delaware.gov",
    sosUrl: "https://corp.delaware.gov",
    taxDeptUrl: "https://revenue.delaware.gov",
    areaCodesRange: "302",
    zipCodesRange: "19701 – 19980",
    largestCity: "Wilmington",
    region: "Mid-Atlantic",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "1,948 sq mi",
    population: "1,030,000+",
    abbreviation: "DE"
  },
  florida: {
    capital: "Tallahassee",
    motto: "In God We Trust",
    mottoTranslation: "In God We Trust",
    nickname: "The Sunshine State",
    statehood: "March 3, 1845",
    statehoodRank: "27th State",
    bird: "Northern Mockingbird",
    flower: "Orange Blossom",
    tree: "Sabal Palm",
    song: "Old Folks at Home",
    insect: "Zebra Longwing Butterfly",
    fish: "Sailfish / Largemouth Bass",
    freshwaterFish: "Largemouth Bass",
    saltwaterFish: "Sailfish",
    mineral: "Agatized Coral",
    gemstone: "Moonstone",
    beverage: "Orange Juice",
    quarterYear: "2004",
    highestPoint: "Britton Hill: 345 ft (105 m)",
    lowestPoint: "Atlantic Ocean / Gulf: 0 ft (0 m)",
    stateWebsite: "https://www.myflorida.com",
    sosUrl: "https://dos.fl.gov",
    taxDeptUrl: "https://floridarevenue.com",
    areaCodesRange: "239, 305, 321, 352, 386, 407, 561, 727, 772, 786, 813, 850, 863, 904, 941, 954",
    zipCodesRange: "32003 – 34997",
    largestCity: "Jacksonville",
    region: "Southeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "65,757 sq mi",
    population: "22,600,000+",
    abbreviation: "FL"
  },
  georgia: {
    capital: "Atlanta",
    motto: "Wisdom, Justice, and Moderation",
    mottoTranslation: "Wisdom, Justice, and Moderation",
    nickname: "The Peach State",
    statehood: "January 2, 1788",
    statehoodRank: "4th State",
    bird: "Brown Thrasher",
    flower: "Cherokee Rose",
    tree: "Live Oak",
    song: "Georgia on My Mind",
    insect: "Honeybee",
    fish: "Largemouth Bass",
    mineral: "Quartz",
    gemstone: "Quartz",
    beverage: "Sweet Tea",
    quarterYear: "1999",
    highestPoint: "Brasstown Bald: 4,784 ft (1,458 m)",
    lowestPoint: "Atlantic Ocean: 0 ft (0 m)",
    stateWebsite: "https://georgia.gov",
    sosUrl: "https://sos.ga.gov",
    taxDeptUrl: "https://dor.georgia.gov",
    areaCodesRange: "229, 404, 470, 478, 678, 706, 762, 770, 912",
    zipCodesRange: "30002 – 39901",
    largestCity: "Atlanta",
    region: "Southeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "59,425 sq mi",
    population: "11,000,000+",
    abbreviation: "GA"
  },
  hawaii: {
    capital: "Honolulu",
    motto: "Ua Mau ke Ea o ka ʻĀina i ka Pono",
    mottoTranslation: "The Life of the Land is Perpetuated in Righteousness",
    nickname: "The Aloha State",
    statehood: "August 21, 1959",
    statehoodRank: "50th State",
    bird: "Nēnē (Hawaiian Goose)",
    flower: "Yellow Hibiscus",
    tree: "Kukui Tree (Candlenut)",
    song: "Hawaiʻi Ponoʻī",
    insect: "Kamehameha Butterfly",
    fish: "Humuhumunukunukuāpuaʻa",
    mineral: "Black Coral",
    gemstone: "Black Coral",
    beverage: "Fruit Juice",
    quarterYear: "2008",
    highestPoint: "Mauna Kea: 13,796 ft (4,205 m)",
    lowestPoint: "Pacific Ocean: 0 ft (0 m)",
    stateWebsite: "https://hawaii.gov",
    sosUrl: "https://cca.hawaii.gov/breg",
    taxDeptUrl: "https://tax.hawaii.gov",
    areaCodesRange: "808",
    zipCodesRange: "96701 – 96863",
    largestCity: "Honolulu",
    region: "Pacific Islands",
    timezone: "Hawaii Standard Time (HST - No DST)",
    landArea: "10,931 sq mi",
    population: "1,440,000+",
    abbreviation: "HI"
  },
  idaho: {
    capital: "Boise",
    motto: "Esto Perpetua",
    mottoTranslation: "Let It Be Perpetual",
    nickname: "The Gem State",
    statehood: "July 3, 1890",
    statehoodRank: "43rd State",
    bird: "Mountain Bluebird",
    flower: "Syringa",
    tree: "Western White Pine",
    song: "Here We Have Idaho",
    insect: "Monarch Butterfly",
    fish: "Cutthroat Trout",
    mineral: "Star Garnet",
    gemstone: "Star Garnet",
    beverage: "Water",
    quarterYear: "2007",
    highestPoint: "Borah Peak: 12,662 ft (3,859 m)",
    lowestPoint: "Snake River: 710 ft (216 m)",
    stateWebsite: "https://idaho.gov",
    sosUrl: "https://sos.idaho.gov",
    taxDeptUrl: "https://tax.idaho.gov",
    areaCodesRange: "208, 986",
    zipCodesRange: "83201 – 83877",
    largestCity: "Boise",
    region: "Pacific Northwest / West",
    timezone: "Mountain / Pacific Time",
    landArea: "83,569 sq mi",
    population: "1,960,000+",
    abbreviation: "ID"
  },
  illinois: {
    capital: "Springfield",
    motto: "State Sovereignty, National Union",
    mottoTranslation: "State Sovereignty, National Union",
    nickname: "Prairie State",
    statehood: "December 3, 1818",
    statehoodRank: "21st State",
    bird: "Northern Cardinal",
    flower: "Violet",
    tree: "White Oak",
    song: "Illinois",
    insect: "Monarch Butterfly",
    fish: "Bluegill",
    mineral: "Fluorite",
    gemstone: "Fluorite",
    beverage: "Milk",
    quarterYear: "2003",
    highestPoint: "Charles Mound: 1,235 ft (376 m)",
    lowestPoint: "Mississippi River: 279 ft (85 m)",
    stateWebsite: "https://illinois.gov",
    sosUrl: "https://www.ilsos.gov",
    taxDeptUrl: "https://tax.illinois.gov",
    areaCodesRange: "217, 309, 312, 618, 630, 708, 773, 815, 847",
    zipCodesRange: "60001 – 62999",
    largestCity: "Chicago",
    region: "Midwest",
    timezone: "Central Time (CST/CDT)",
    landArea: "57,914 sq mi",
    population: "12,580,000+",
    abbreviation: "IL"
  },
  indiana: {
    capital: "Indianapolis",
    motto: "The Crossroads of America",
    mottoTranslation: "The Crossroads of America",
    nickname: "The Hoosier State",
    statehood: "December 11, 1816",
    statehoodRank: "19th State",
    bird: "Northern Cardinal",
    flower: "Peony",
    tree: "Tulip Tree",
    song: "On the Banks of the Wabash, Far Away",
    insect: "Say's Firefly",
    fish: "Largemouth Bass",
    mineral: "Salem Limestone",
    beverage: "Water",
    quarterYear: "2002",
    highestPoint: "Hoosier Hill: 1,257 ft (383 m)",
    lowestPoint: "Ohio River: 320 ft (98 m)",
    stateWebsite: "https://in.gov",
    sosUrl: "https://inbiz.in.gov",
    taxDeptUrl: "https://www.in.gov/dor",
    areaCodesRange: "219, 260, 317, 463, 765, 812, 930",
    zipCodesRange: "46001 – 47997",
    largestCity: "Indianapolis",
    region: "Midwest",
    timezone: "Eastern / Central Time",
    landArea: "36,419 sq mi",
    population: "6,830,000+",
    abbreviation: "IN"
  },
  iowa: {
    capital: "Des Moines",
    motto: "Our Liberties We Prize and Our Rights We Will Maintain",
    mottoTranslation: "Our Liberties We Prize",
    nickname: "The Hawkeye State",
    statehood: "December 28, 1846",
    statehoodRank: "29th State",
    bird: "Eastern Goldfinch",
    flower: "Wild Prairie Rose",
    tree: "Oak",
    song: "The Song of Iowa",
    insect: "Honeybee",
    fish: "Channel Catfish",
    mineral: "Geode",
    gemstone: "Quartz Geode",
    beverage: "Milk",
    quarterYear: "2004",
    highestPoint: "Hawkeye Point: 1,670 ft (509 m)",
    lowestPoint: "Mississippi River: 480 ft (146 m)",
    stateWebsite: "https://iowa.gov",
    sosUrl: "https://sos.iowa.gov",
    taxDeptUrl: "https://tax.iowa.gov",
    areaCodesRange: "319, 515, 563, 641, 712",
    zipCodesRange: "50001 – 52809",
    largestCity: "Des Moines",
    region: "Midwest",
    timezone: "Central Time (CST/CDT)",
    landArea: "56,273 sq mi",
    population: "3,200,000+",
    abbreviation: "IA"
  },
  kansas: {
    capital: "Topeka",
    motto: "Ad Astra Per Aspera",
    mottoTranslation: "To the Stars Through Difficulties",
    nickname: "The Sunflower State",
    statehood: "January 29, 1861",
    statehoodRank: "34th State",
    bird: "Western Meadowlark",
    flower: "Wild Native Sunflower",
    tree: "Cottonwood",
    song: "Home on the Range",
    insect: "Honeybee",
    fish: "Channel Catfish",
    mineral: "Galena",
    beverage: "Milk",
    quarterYear: "2005",
    highestPoint: "Mount Sunflower: 4,039 ft (1,231 m)",
    lowestPoint: "Verdigris River: 679 ft (207 m)",
    stateWebsite: "https://kansas.gov",
    sosUrl: "https://sos.ks.gov",
    taxDeptUrl: "https://www.ksrevenue.gov",
    areaCodesRange: "316, 620, 785, 913",
    zipCodesRange: "66002 – 67954",
    largestCity: "Wichita",
    region: "Midwest / Great Plains",
    timezone: "Central / Mountain Time",
    landArea: "82,278 sq mi",
    population: "2,937,000+",
    abbreviation: "KS"
  },
  kentucky: {
    capital: "Frankfort",
    motto: "Deo Gratiam Habeamus",
    mottoTranslation: "Let Us Be Grateful to God / United We Stand",
    nickname: "The Bluegrass State",
    statehood: "June 1, 1792",
    statehoodRank: "15th State",
    bird: "Northern Cardinal",
    flower: "Goldenrod",
    tree: "Tulip Poplar",
    song: "My Old Kentucky Home",
    insect: "Honeybee",
    fish: "Kentucky Spotted Bass",
    mineral: "Coal",
    gemstone: "Freshwater Pearl",
    beverage: "Milk",
    quarterYear: "2001",
    highestPoint: "Black Mountain: 4,145 ft (1,263 m)",
    lowestPoint: "Mississippi River: 257 ft (78 m)",
    stateWebsite: "https://kentucky.gov",
    sosUrl: "https://www.sos.ky.gov",
    taxDeptUrl: "https://revenue.ky.gov",
    areaCodesRange: "270, 364, 502, 606, 859",
    zipCodesRange: "40003 – 42788",
    largestCity: "Louisville",
    region: "Southeast / East South Central",
    timezone: "Eastern / Central Time",
    landArea: "40,408 sq mi",
    population: "4,510,000+",
    abbreviation: "KY"
  },
  louisiana: {
    capital: "Baton Rouge",
    motto: "Union, Justice, and Confidence",
    mottoTranslation: "Union, Justice, and Confidence",
    nickname: "Pelican State",
    statehood: "April 30, 1812",
    statehoodRank: "18th State",
    bird: "Brown Pelican",
    flower: "Magnolia",
    tree: "Bald Cypress",
    song: "You Are My Sunshine",
    insect: "Honeybee",
    fish: "White Crappie",
    mineral: "Agate",
    gemstone: "Agate",
    beverage: "Milk",
    quarterYear: "2002",
    highestPoint: "Driskill Mountain: 535 ft (163 m)",
    lowestPoint: "New Orleans: -8 ft (-2.4 m)",
    stateWebsite: "https://louisiana.gov",
    sosUrl: "https://www.sos.la.gov",
    taxDeptUrl: "https://revenue.louisiana.gov",
    areaCodesRange: "225, 318, 337, 504, 985",
    zipCodesRange: "70001 – 71497",
    largestCity: "New Orleans",
    region: "Southeast",
    timezone: "Central Time (CST/CDT)",
    landArea: "52,378 sq mi",
    population: "4,590,000+",
    abbreviation: "LA"
  },
  maine: {
    capital: "Augusta",
    motto: "Dirigo",
    mottoTranslation: "I Lead",
    nickname: "The Pine Tree State",
    statehood: "March 15, 1820",
    statehoodRank: "23rd State",
    bird: "Black-capped Chickadee",
    flower: "White Pine Cone and Tassel",
    tree: "Eastern White Pine",
    song: "State of Maine Song",
    insect: "Honeybee",
    fish: "Landlocked Salmon",
    mineral: "Tourmaline",
    gemstone: "Tourmaline",
    beverage: "Moxie",
    quarterYear: "2003",
    highestPoint: "Mount Katahdin: 5,267 ft (1,605 m)",
    lowestPoint: "Atlantic Ocean: 0 ft (0 m)",
    stateWebsite: "https://maine.gov",
    sosUrl: "https://www.maine.gov/sos",
    taxDeptUrl: "https://www.maine.gov/revenue",
    areaCodesRange: "207",
    zipCodesRange: "03901 – 04992",
    largestCity: "Portland",
    region: "New England",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "35,385 sq mi",
    population: "1,385,000+",
    abbreviation: "ME"
  },
  maryland: {
    capital: "Annapolis",
    motto: "Fatti Maschii, Parole Femine",
    mottoTranslation: "Manly Deeds, Womanly Words",
    nickname: "The Old Line State",
    statehood: "April 28, 1788",
    statehoodRank: "7th State",
    bird: "Baltimore Oriole",
    flower: "Black-eyed Susan",
    tree: "White Oak",
    song: "Maryland, My Maryland",
    insect: "Baltimore Checkerspot Butterfly",
    fish: "Rockfish (Striped Bass)",
    mineral: "Agate",
    beverage: "Milk",
    quarterYear: "2000",
    highestPoint: "Hoye-Crest: 3,360 ft (1,024 m)",
    lowestPoint: "Atlantic Ocean: 0 ft (0 m)",
    stateWebsite: "https://maryland.gov",
    sosUrl: "https://sos.maryland.gov",
    taxDeptUrl: "https://www.marylandtaxes.gov",
    areaCodesRange: "240, 301, 410, 443, 667",
    zipCodesRange: "20601 – 21930",
    largestCity: "Baltimore",
    region: "Mid-Atlantic",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "12,407 sq mi",
    population: "6,160,000+",
    abbreviation: "MD"
  },
  massachusetts: {
    capital: "Boston",
    motto: "Ense Petit Placidam Sub Libertate Quietem",
    mottoTranslation: "By the Sword We Seek Peace, But Peace Only Under Liberty",
    nickname: "The Bay State",
    statehood: "February 6, 1788",
    statehoodRank: "6th State",
    bird: "Black-capped Chickadee",
    flower: "Mayflower",
    tree: "American Elm",
    song: "All Hail to Massachusetts",
    insect: "Ladybug",
    fish: "Cod",
    mineral: "Rhodonite",
    gemstone: "Rhodonite",
    beverage: "Cranberry Juice",
    quarterYear: "2000",
    highestPoint: "Mount Greylock: 3,489 ft (1,063 m)",
    lowestPoint: "Atlantic Ocean: 0 ft (0 m)",
    stateWebsite: "https://mass.gov",
    sosUrl: "https://www.sec.state.ma.us",
    taxDeptUrl: "https://www.mass.gov/orgs/massachusetts-department-of-revenue",
    areaCodesRange: "339, 351, 413, 508, 617, 774, 781, 857, 978",
    zipCodesRange: "01001 – 02791",
    largestCity: "Boston",
    region: "New England",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "10,554 sq mi",
    population: "6,980,000+",
    abbreviation: "MA"
  },
  michigan: {
    capital: "Lansing",
    motto: "Si Quaeris Peninsulam Amoenam Circumspice",
    mottoTranslation: "If You Seek a Pleasant Peninsula, Look About You",
    nickname: "The Great Lakes State",
    statehood: "January 26, 1837",
    statehoodRank: "26th State",
    bird: "American Robin",
    flower: "Apple Blossom",
    tree: "Eastern White Pine",
    song: "Michigan, My Michigan",
    insect: "Monarch Butterfly",
    fish: "Brook Trout",
    mineral: "Native Copper",
    gemstone: "Chlorastrolite",
    beverage: "Milk",
    quarterYear: "2004",
    highestPoint: "Mount Arvon: 1,979 ft (603 m)",
    lowestPoint: "Lake Erie: 571 ft (174 m)",
    stateWebsite: "https://michigan.gov",
    sosUrl: "https://www.michigan.gov/sos",
    taxDeptUrl: "https://www.michigan.gov/taxes",
    areaCodesRange: "231, 248, 269, 313, 517, 586, 616, 734, 810, 906, 947, 989",
    zipCodesRange: "48001 – 49971",
    largestCity: "Detroit",
    region: "Midwest",
    timezone: "Eastern / Central Time",
    landArea: "96,716 sq mi",
    population: "10,030,000+",
    abbreviation: "MI"
  },
  minnesota: {
    capital: "St. Paul",
    motto: "L'Étoile du Nord",
    mottoTranslation: "The Star of the North",
    nickname: "Land of 10,000 Lakes",
    statehood: "May 11, 1858",
    statehoodRank: "32nd State",
    bird: "Common Loon",
    flower: "Pink and White Lady's Slipper",
    tree: "Red Pine",
    song: "Hail! Minnesota",
    insect: "Rusty Patched Bumblebee",
    fish: "Walleye",
    mineral: "Iron Ore",
    gemstone: "Lake Superior Agate",
    beverage: "Milk",
    quarterYear: "2005",
    highestPoint: "Eagle Mountain: 2,301 ft (701 m)",
    lowestPoint: "Lake Superior: 602 ft (183 m)",
    stateWebsite: "https://mn.gov",
    sosUrl: "https://www.sos.state.mn.us",
    taxDeptUrl: "https://www.revenue.state.mn.us",
    areaCodesRange: "218, 320, 507, 612, 651, 763, 952",
    zipCodesRange: "55001 – 56763",
    largestCity: "Minneapolis",
    region: "Midwest",
    timezone: "Central Time (CST/CDT)",
    landArea: "86,935 sq mi",
    population: "5,717,000+",
    abbreviation: "MN"
  },
  mississippi: {
    capital: "Jackson",
    motto: "Virtute et Armis",
    mottoTranslation: "By Valor and Arms",
    nickname: "The Magnolia State",
    statehood: "December 10, 1817",
    statehoodRank: "20th State",
    bird: "Northern Mockingbird",
    flower: "Magnolia",
    tree: "Magnolia",
    song: "Go, Mississippi",
    insect: "Honeybee",
    fish: "Largemouth Bass",
    mineral: "Petrified Wood",
    beverage: "Milk",
    quarterYear: "2002",
    highestPoint: "Woodall Mountain: 806 ft (246 m)",
    lowestPoint: "Gulf of Mexico: 0 ft (0 m)",
    stateWebsite: "https://ms.gov",
    sosUrl: "https://www.sos.ms.gov",
    taxDeptUrl: "https://www.dor.ms.gov",
    areaCodesRange: "228, 601, 662, 769",
    zipCodesRange: "38601 – 39776",
    largestCity: "Jackson",
    region: "Southeast",
    timezone: "Central Time (CST/CDT)",
    landArea: "48,432 sq mi",
    population: "2,940,000+",
    abbreviation: "MS"
  },
  missouri: {
    capital: "Jefferson City",
    motto: "Salus Populi Suprema Lex Esto",
    mottoTranslation: "The Welfare of the People Shall Be the Supreme Law",
    nickname: "Show Me State",
    statehood: "August 10, 1821",
    statehoodRank: "24th State",
    bird: "Eastern Bluebird",
    flower: "White Hawthorn",
    tree: "Flowering Dogwood",
    song: "Missouri Waltz",
    insect: "Honeybee",
    fish: "Paddlesfish",
    mineral: "Galena",
    gemstone: "Mozarkite",
    beverage: "Milk",
    quarterYear: "2003",
    highestPoint: "Taum Sauk Mountain: 1,772 ft (540 m)",
    lowestPoint: "St. Francis River: 230 ft (70 m)",
    stateWebsite: "https://mo.gov",
    sosUrl: "https://www.sos.mo.gov",
    taxDeptUrl: "https://dor.mo.gov",
    areaCodesRange: "314, 417, 573, 636, 660, 816",
    zipCodesRange: "63001 – 65899",
    largestCity: "Kansas City",
    region: "Midwest",
    timezone: "Central Time (CST/CDT)",
    landArea: "69,707 sq mi",
    population: "6,178,000+",
    abbreviation: "MO"
  },
  montana: {
    capital: "Helena",
    motto: "Oro y Plata",
    mottoTranslation: "Gold and Silver",
    nickname: "Treasure State",
    statehood: "November 8, 1889",
    statehoodRank: "41st State",
    bird: "Western Meadowlark",
    flower: "Bitterroot",
    tree: "Ponderosa Pine",
    song: "Montana",
    insect: "Mourning Cloak Butterfly",
    fish: "Blackspotted Cutthroat Trout",
    mineral: "Sapphire and Agate",
    gemstone: "Yogo Sapphire",
    beverage: "Milk",
    quarterYear: "2007",
    highestPoint: "Granite Peak: 12,799 ft (3,901 m)",
    lowestPoint: "Kootenai River: 1,800 ft (549 m)",
    stateWebsite: "https://mt.gov",
    sosUrl: "https://sosmt.gov",
    taxDeptUrl: "https://mtrevenue.gov",
    areaCodesRange: "406",
    zipCodesRange: "59001 – 59937",
    largestCity: "Billings",
    region: "West / Mountain",
    timezone: "Mountain Time (MST/MDT)",
    landArea: "147,040 sq mi",
    population: "1,123,000+",
    abbreviation: "MT"
  },
  nebraska: {
    capital: "Lincoln",
    motto: "Equality Before the Law",
    mottoTranslation: "Equality Before the Law",
    nickname: "Cornhusker State",
    statehood: "March 1, 1867",
    statehoodRank: "37th State",
    bird: "Western Meadowlark",
    flower: "Goldenrod",
    tree: "Cottonwood",
    song: "Beautiful Nebraska",
    insect: "Honeybee",
    fish: "Channel Catfish",
    mineral: "Prairie Agate",
    beverage: "Milk",
    quarterYear: "2006",
    highestPoint: "Panorama Point: 5,429 ft (1,655 m)",
    lowestPoint: "Missouri River: 840 ft (256 m)",
    stateWebsite: "https://nebraska.gov",
    sosUrl: "https://sos.nebraska.gov",
    taxDeptUrl: "https://revenue.nebraska.gov",
    areaCodesRange: "308, 402, 531",
    zipCodesRange: "68001 – 69367",
    largestCity: "Omaha",
    region: "Midwest",
    timezone: "Central / Mountain Time",
    landArea: "77,358 sq mi",
    population: "1,968,000+",
    abbreviation: "NE"
  },
  nevada: {
    capital: "Carson City",
    motto: "All for Our Country",
    mottoTranslation: "All for Our Country",
    nickname: "The Silver State",
    statehood: "October 31, 1864",
    statehoodRank: "36th State",
    bird: "Mountain Bluebird",
    flower: "Sagebrush",
    tree: "Single-leaf Pinyon Pine",
    song: "Home Means Nevada",
    insect: "Viceroy Butterfly",
    fish: "Lahontan Cutthroat Trout",
    mineral: "Silver",
    gemstone: "Nevada Virgin Valley Black Fire Opal",
    beverage: "Milk",
    quarterYear: "2006",
    highestPoint: "Boundary Peak: 13,140 ft (4,005 m)",
    lowestPoint: "Colorado River: 479 ft (146 m)",
    stateWebsite: "https://nv.gov",
    sosUrl: "https://www.nvsos.gov",
    taxDeptUrl: "https://tax.nv.gov",
    areaCodesRange: "702, 725, 775",
    zipCodesRange: "88901 – 89883",
    largestCity: "Las Vegas",
    region: "West",
    timezone: "Pacific Time (PST/PDT)",
    landArea: "110,572 sq mi",
    population: "3,177,000+",
    abbreviation: "NV"
  },
  newhampshire: {
    capital: "Concord",
    motto: "Live Free or Die",
    mottoTranslation: "Live Free or Die",
    nickname: "Granite State",
    statehood: "June 21, 1788",
    statehoodRank: "9th State",
    bird: "Purple Finch",
    flower: "Purple Lilac",
    tree: "White Birch",
    song: "Old New Hampshire",
    insect: "Ladybug",
    fish: "Brook Trout",
    mineral: "Granite",
    gemstone: "Smoky Quartz",
    beverage: "Apple Cider",
    quarterYear: "2000",
    highestPoint: "Mount Washington: 6,288 ft (1,917 m)",
    lowestPoint: "Atlantic Ocean: 0 ft (0 m)",
    stateWebsite: "https://nh.gov",
    sosUrl: "https://www.sos.nh.gov",
    taxDeptUrl: "https://www.revenue.nh.gov",
    areaCodesRange: "603",
    zipCodesRange: "03031 – 03897",
    largestCity: "Manchester",
    region: "New England",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "9,349 sq mi",
    population: "1,395,000+",
    abbreviation: "NH"
  },
  newjersey: {
    capital: "Trenton",
    motto: "Liberty and Prosperity",
    mottoTranslation: "Liberty and Prosperity",
    nickname: "Garden State",
    statehood: "December 18, 1787",
    statehoodRank: "3rd State",
    bird: "Eastern Goldfinch",
    flower: "Violet",
    tree: "Red Oak",
    song: "I'm From New Jersey",
    insect: "Honeybee",
    fish: "Brook Trout",
    mineral: "Franklinite",
    beverage: "Milk",
    quarterYear: "1999",
    highestPoint: "High Point: 1,803 ft (550 m)",
    lowestPoint: "Atlantic Ocean: 0 ft (0 m)",
    stateWebsite: "https://nj.gov",
    sosUrl: "https://www.nj.gov/state",
    taxDeptUrl: "https://www.state.nj.us/treasury/taxation",
    areaCodesRange: "201, 551, 609, 640, 732, 848, 856, 862, 908, 973",
    zipCodesRange: "07001 – 08989",
    largestCity: "Newark",
    region: "Mid-Atlantic",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "8,723 sq mi",
    population: "9,260,000+",
    abbreviation: "NJ"
  },
  newmexico: {
    capital: "Santa Fe",
    motto: "Crescit Eundo",
    mottoTranslation: "It Grows as It Goes",
    nickname: "Land of Enchantment",
    statehood: "January 6, 1912",
    statehoodRank: "47th State",
    bird: "Roadrunner",
    flower: "Yucca Flower",
    tree: "Piñon Pine",
    song: "O Fair New Mexico",
    insect: "Tarantula Hawk Wasp",
    fish: "Rio Grande Cutthroat Trout",
    mineral: "Peridot",
    gemstone: "Turquoise",
    beverage: "Milk",
    quarterYear: "2008",
    highestPoint: "Wheeler Peak: 13,161 ft (4,011 m)",
    lowestPoint: "Red Bluff Reservoir: 2,842 ft (866 m)",
    stateWebsite: "https://newmexico.gov",
    sosUrl: "https://www.sos.nm.gov",
    taxDeptUrl: "https://www.tax.newmexico.gov",
    areaCodesRange: "505, 575",
    zipCodesRange: "87001 – 88439",
    largestCity: "Albuquerque",
    region: "Southwest",
    timezone: "Mountain Time (MST/MDT)",
    landArea: "121,590 sq mi",
    population: "2,113,000+",
    abbreviation: "NM"
  },
  newyork: {
    capital: "Albany",
    motto: "Excelsior",
    mottoTranslation: "Ever Upward",
    nickname: "Empire State",
    statehood: "July 26, 1788",
    statehoodRank: "11th State",
    bird: "Eastern Bluebird",
    flower: "Rose",
    tree: "Sugar Maple",
    song: "I Love New York",
    insect: "Nine-spotted Ladybug",
    fish: "Brook Trout",
    mineral: "Harker Diamond / Garnet",
    gemstone: "Almandine Garnet",
    beverage: "Milk",
    quarterYear: "2001",
    highestPoint: "Mount Marcy: 5,344 ft (1,629 m)",
    lowestPoint: "Atlantic Ocean: 0 ft (0 m)",
    stateWebsite: "https://ny.gov",
    sosUrl: "https://dos.ny.gov",
    taxDeptUrl: "https://www.tax.ny.gov",
    areaCodesRange: "212, 315, 332, 347, 516, 518, 607, 631, 646, 716, 718, 845, 914, 917, 929",
    zipCodesRange: "10001 – 14925",
    largestCity: "New York City",
    region: "Mid-Atlantic / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "54,555 sq mi",
    population: "19,670,000+",
    abbreviation: "NY"
  },
  northcarolina: {
    capital: "Raleigh",
    motto: "Esse Quam Videri",
    mottoTranslation: "To Be, Rather Than to Seem",
    nickname: "Tar Heel State",
    statehood: "November 21, 1789",
    statehoodRank: "12th State",
    bird: "Northern Cardinal",
    flower: "Flowering Dogwood",
    tree: "Pine",
    song: "The Old North State",
    insect: "Honeybee",
    fish: "Channel Bass (Red Drum)",
    mineral: "Gold",
    gemstone: "Emerald",
    beverage: "Milk",
    quarterYear: "2001",
    highestPoint: "Mount Mitchell: 6,684 ft (2,037 m)",
    lowestPoint: "Atlantic Ocean: 0 ft (0 m)",
    stateWebsite: "https://nc.gov",
    sosUrl: "https://www.sosnc.gov",
    taxDeptUrl: "https://www.ncdor.gov",
    areaCodesRange: "252, 336, 704, 828, 910, 919, 980, 984",
    zipCodesRange: "27006 – 28909",
    largestCity: "Charlotte",
    region: "Southeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "53,819 sq mi",
    population: "10,700,000+",
    abbreviation: "NC"
  },
  northdakota: {
    capital: "Bismarck",
    motto: "Liberty and Union, Now and Forever, One and Inseparable",
    mottoTranslation: "Liberty and Union",
    nickname: "Peace Garden State",
    statehood: "November 2, 1889",
    statehoodRank: "39th State",
    bird: "Western Meadowlark",
    flower: "Wild Prairie Rose",
    tree: "American Elm",
    song: "North Dakota Hymn",
    insect: "Convergent Lady Beetle",
    fish: "Northern Pike",
    mineral: "Lignite Coal",
    beverage: "Milk",
    quarterYear: "2006",
    highestPoint: "White Butte: 3,506 ft (1,069 m)",
    lowestPoint: "Red River of the North: 750 ft (229 m)",
    stateWebsite: "https://nd.gov",
    sosUrl: "https://sos.nd.gov",
    taxDeptUrl: "https://www.tax.nd.gov",
    areaCodesRange: "701",
    zipCodesRange: "58001 – 58856",
    largestCity: "Fargo",
    region: "Midwest / Great Plains",
    timezone: "Central / Mountain Time",
    landArea: "70,698 sq mi",
    population: "779,000+",
    abbreviation: "ND"
  },
  ohio: {
    capital: "Columbus",
    motto: "With God, All Things Are Possible",
    mottoTranslation: "With God, All Things Are Possible",
    nickname: "Buckeye State",
    statehood: "March 1, 1803",
    statehoodRank: "17th State",
    bird: "Northern Cardinal",
    flower: "Scarlet Carnation",
    tree: "Ohio Buckeye",
    song: "Beautiful Ohio",
    insect: "Ladybug",
    fish: "Walleye",
    mineral: "Flint",
    gemstone: "Ohio Flint",
    beverage: "Tomato Juice",
    quarterYear: "2002",
    highestPoint: "Campbell Hill: 1,549 ft (472 m)",
    lowestPoint: "Ohio River: 455 ft (139 m)",
    stateWebsite: "https://ohio.gov",
    sosUrl: "https://www.ohiosos.gov",
    taxDeptUrl: "https://tax.ohio.gov",
    areaCodesRange: "216, 234, 330, 419, 440, 513, 567, 614, 740, 937",
    zipCodesRange: "43001 – 45999",
    largestCity: "Columbus",
    region: "Midwest",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "44,825 sq mi",
    population: "11,780,000+",
    abbreviation: "OH"
  },
  oklahoma: {
    capital: "Oklahoma City",
    motto: "Labor Omnia Vincit",
    mottoTranslation: "Labor Conquers All Things",
    nickname: "Sooner State",
    statehood: "November 16, 1907",
    statehoodRank: "46th State",
    bird: "Scissor-tailed Flycatcher",
    flower: "Oklahoma Rose",
    tree: "Redbud",
    song: "Oklahoma!",
    insect: "Honeybee",
    fish: "White Bass",
    mineral: "Rose Rock (Barite Rose)",
    gemstone: "Barite Rose",
    beverage: "Milk",
    quarterYear: "2008",
    highestPoint: "Black Mesa: 4,973 ft (1,516 m)",
    lowestPoint: "Little River: 289 ft (88 m)",
    stateWebsite: "https://oklahoma.gov",
    sosUrl: "https://www.sos.ok.gov",
    taxDeptUrl: "https://oklahoma.gov/service-oklahoma/tax.html",
    areaCodesRange: "405, 539, 580, 918",
    zipCodesRange: "73001 – 74966",
    largestCity: "Oklahoma City",
    region: "South Central",
    timezone: "Central Time (CST/CDT)",
    landArea: "69,899 sq mi",
    population: "4,020,000+",
    abbreviation: "OK"
  },
  oregon: {
    capital: "Salem",
    motto: "Alis Volat Propriis",
    mottoTranslation: "She Flies With Her Own Wings",
    nickname: "Beaver State",
    statehood: "February 14, 1859",
    statehoodRank: "33rd State",
    bird: "Western Meadowlark",
    flower: "Oregon Grape",
    tree: "Douglas Fir",
    song: "Oregon, My Oregon",
    insect: "Oregon Swallowtail Butterfly",
    fish: "Chinook Salmon",
    mineral: "Sunstone",
    gemstone: "Oregon Sunstone",
    beverage: "Milk",
    quarterYear: "2005",
    highestPoint: "Mount Hood: 11,249 ft (3,429 m)",
    lowestPoint: "Pacific Ocean: 0 ft (0 m)",
    stateWebsite: "https://oregon.gov",
    sosUrl: "https://sos.oregon.gov",
    taxDeptUrl: "https://www.oregon.gov/dor",
    areaCodesRange: "458, 503, 541, 971",
    zipCodesRange: "97001 – 97920",
    largestCity: "Portland",
    region: "Pacific Northwest",
    timezone: "Pacific / Mountain Time",
    landArea: "98,378 sq mi",
    population: "4,240,000+",
    abbreviation: "OR"
  },
  pennsylvania: {
    capital: "Harrisburg",
    motto: "Virtue, Liberty, and Independence",
    mottoTranslation: "Virtue, Liberty, and Independence",
    nickname: "Keystone State",
    statehood: "December 12, 1787",
    statehoodRank: "2nd State",
    bird: "Ruffed Grouse",
    flower: "Mountain Laurel",
    tree: "Eastern Hemlock",
    song: "Pennsylvania",
    insect: "Pennsylvania Firefly",
    fish: "Brook Trout",
    mineral: "Iron Ore",
    beverage: "Milk",
    quarterYear: "1999",
    highestPoint: "Mount Davis: 3,213 ft (979 m)",
    lowestPoint: "Delaware River: 0 ft (0 m)",
    stateWebsite: "https://pa.gov",
    sosUrl: "https://www.dos.pa.gov",
    taxDeptUrl: "https://www.revenue.pa.gov",
    areaCodesRange: "215, 267, 272, 412, 484, 570, 610, 717, 724, 814, 878",
    zipCodesRange: "15001 – 19612",
    largestCity: "Philadelphia",
    region: "Mid-Atlantic",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "46,054 sq mi",
    population: "12,960,000+",
    abbreviation: "PA"
  },
  rhodeisland: {
    capital: "Providence",
    motto: "Hope",
    mottoTranslation: "Hope",
    nickname: "The Ocean State",
    statehood: "May 29, 1790",
    statehoodRank: "13th State",
    bird: "Rhode Island Red",
    flower: "Violet",
    tree: "Red Maple",
    song: "Rhode Island's It for Me",
    insect: "American Burying Beetle",
    fish: "Striped Bass",
    mineral: "Cumberlandite",
    gemstone: "Bowenite",
    beverage: "Coffee Milk",
    quarterYear: "2001",
    highestPoint: "Jerimoth Hill: 812 ft (247 m)",
    lowestPoint: "Atlantic Ocean: 0 ft (0 m)",
    stateWebsite: "https://ri.gov",
    sosUrl: "https://www.sos.ri.gov",
    taxDeptUrl: "https://tax.ri.gov",
    areaCodesRange: "401",
    zipCodesRange: "02801 – 02940",
    largestCity: "Providence",
    region: "New England",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "1,214 sq mi",
    population: "1,095,000+",
    abbreviation: "RI"
  },
  southcarolina: {
    capital: "Columbia",
    motto: "Dum Spiro Spero / Animis Opibusque Parati",
    mottoTranslation: "While I Breathe, I Hope / Prepared in Mind and Resources",
    nickname: "Palmetto State",
    statehood: "May 23, 1788",
    statehoodRank: "8th State",
    bird: "Carolina Wren",
    flower: "Yellow Jessamine",
    tree: "Sabal Palmetto",
    song: "Carolina",
    insect: "Carolina Mantis",
    fish: "Striped Bass",
    mineral: "Amethyst",
    gemstone: "Amethyst",
    beverage: "Milk",
    quarterYear: "2000",
    highestPoint: "Sassafras Mountain: 3,556 ft (1,084 m)",
    lowestPoint: "Atlantic Ocean: 0 ft (0 m)",
    stateWebsite: "https://sc.gov",
    sosUrl: "https://sos.sc.gov",
    taxDeptUrl: "https://dor.sc.gov",
    areaCodesRange: "803, 843, 854, 864",
    zipCodesRange: "29001 – 29945",
    largestCity: "Charleston",
    region: "Southeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "32,020 sq mi",
    population: "5,280,000+",
    abbreviation: "SC"
  },
  southdakota: {
    capital: "Pierre",
    motto: "Under God the People Rule",
    mottoTranslation: "Under God the People Rule",
    nickname: "Mount Rushmore State",
    statehood: "November 2, 1889",
    statehoodRank: "40th State",
    bird: "Ring-necked Pheasant",
    flower: "American Pasque",
    tree: "Black Hills Spruce",
    song: "Hail, South Dakota!",
    insect: "Honeybee",
    fish: "Walleye",
    mineral: "Rose Quartz",
    gemstone: "Fairburn Agate",
    beverage: "Milk",
    quarterYear: "2006",
    highestPoint: "Black Elk Peak: 7,242 ft (2,207 m)",
    lowestPoint: "Big Stone Lake: 966 ft (294 m)",
    stateWebsite: "https://sd.gov",
    sosUrl: "https://sdsos.gov",
    taxDeptUrl: "https://dor.sd.gov",
    areaCodesRange: "605",
    zipCodesRange: "57001 – 57799",
    largestCity: "Sioux Falls",
    region: "Midwest / Great Plains",
    timezone: "Central / Mountain Time",
    landArea: "77,116 sq mi",
    population: "910,000+",
    abbreviation: "SD"
  },
  tennessee: {
    capital: "Nashville",
    motto: "Agriculture and Commerce",
    mottoTranslation: "Agriculture and Commerce",
    nickname: "The Volunteer State",
    statehood: "June 1, 1796",
    statehoodRank: "16th State",
    bird: "Northern Mockingbird",
    flower: "Iris",
    tree: "Tulip Poplar",
    song: "Tennessee Waltz",
    insect: "Honeybee & Firefly",
    fish: "Smallmouth Bass",
    mineral: "Agate",
    gemstone: "Tennessee Pearl",
    beverage: "Milk",
    quarterYear: "2002",
    highestPoint: "Clingmans Dome: 6,643 ft (2,025 m)",
    lowestPoint: "Mississippi River: 178 ft (54 m)",
    stateWebsite: "https://tn.gov",
    sosUrl: "https://sos.tn.gov",
    taxDeptUrl: "https://www.tn.gov/revenue",
    areaCodesRange: "423, 615, 629, 731, 865, 901, 931",
    zipCodesRange: "37010 – 38589",
    largestCity: "Nashville",
    region: "Southeast",
    timezone: "Eastern / Central Time",
    landArea: "42,144 sq mi",
    population: "7,050,000+",
    abbreviation: "TN"
  },
  texas: {
    capital: "Austin",
    motto: "Friendship",
    mottoTranslation: "Friendship",
    nickname: "Lone Star State",
    statehood: "December 29, 1845",
    statehoodRank: "28th State",
    bird: "Northern Mockingbird",
    flower: "Texas Bluebonnet",
    tree: "Pecan",
    song: "Texas, Our Texas",
    insect: "Monarch Butterfly",
    fish: "Guadalupe Bass",
    mineral: "Silver",
    gemstone: "Texas Blue Topaz",
    beverage: "Water / Milk",
    quarterYear: "2004",
    highestPoint: "Guadalupe Peak: 8,749 ft (2,667 m)",
    lowestPoint: "Gulf of Mexico: 0 ft (0 m)",
    stateWebsite: "https://texas.gov",
    sosUrl: "https://www.sos.state.tx.us",
    taxDeptUrl: "https://comptroller.texas.gov",
    areaCodesRange: "210, 214, 254, 281, 325, 346, 361, 409, 430, 432, 469, 512, 713, 737, 806, 817, 830, 832, 903, 915, 936, 940, 956, 972, 979",
    zipCodesRange: "73301 – 79999",
    largestCity: "Houston",
    region: "South Central",
    timezone: "Central / Mountain Time",
    landArea: "268,596 sq mi",
    population: "30,000,000+",
    abbreviation: "TX"
  },
  utah: {
    capital: "Salt Lake City",
    motto: "Industry",
    mottoTranslation: "Industry",
    nickname: "Beehive State",
    statehood: "January 4, 1896",
    statehoodRank: "45th State",
    bird: "California Gull",
    flower: "Sego Lily",
    tree: "Quaking Aspen",
    song: "Utah, This Is the Place",
    insect: "Honeybee",
    fish: "Bonneville Cutthroat Trout",
    mineral: "Copper",
    gemstone: "Topaz",
    beverage: "Milk",
    quarterYear: "2007",
    highestPoint: "Kings Peak: 13,528 ft (4,123 m)",
    lowestPoint: "Beaver Dam Wash: 2,180 ft (664 m)",
    stateWebsite: "https://utah.gov",
    sosUrl: "https://corporations.utah.gov",
    taxDeptUrl: "https://tax.utah.gov",
    areaCodesRange: "385, 435, 801",
    zipCodesRange: "84001 – 84791",
    largestCity: "Salt Lake City",
    region: "West / Mountain",
    timezone: "Mountain Time (MST/MDT)",
    landArea: "84,899 sq mi",
    population: "3,380,000+",
    abbreviation: "UT"
  },
  vermont: {
    capital: "Montpelier",
    motto: "Freedom and Unity",
    mottoTranslation: "Freedom and Unity",
    nickname: "Green Mountain State",
    statehood: "March 4, 1791",
    statehoodRank: "14th State",
    bird: "Hermit Thrush",
    flower: "Red Clover",
    tree: "Sugar Maple",
    song: "These Green Mountains",
    insect: "Western Honeybee",
    fish: "Brook Trout & Walleye",
    mineral: "Talc",
    gemstone: "Grossularite Garnet",
    beverage: "Milk",
    quarterYear: "2001",
    highestPoint: "Mount Mansfield: 4,393 ft (1,339 m)",
    lowestPoint: "Lake Champlain: 95 ft (29 m)",
    stateWebsite: "https://vermont.gov",
    sosUrl: "https://sos.vermont.gov",
    taxDeptUrl: "https://tax.vermont.gov",
    areaCodesRange: "802",
    zipCodesRange: "05001 – 05907",
    largestCity: "Burlington",
    region: "New England",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "9,616 sq mi",
    population: "647,000+",
    abbreviation: "VT"
  },
  virginia: {
    capital: "Richmond",
    motto: "Sic Semper Tyrannis",
    mottoTranslation: "Thus Always to Tyrants",
    nickname: "Old Dominion",
    statehood: "June 25, 1788",
    statehoodRank: "10th State",
    bird: "Northern Cardinal",
    flower: "American Dogwood",
    tree: "American Dogwood",
    song: "Our Great Virginia",
    insect: "Tiger Swallowtail Butterfly",
    fish: "Brook Trout",
    mineral: "Nelsonite",
    beverage: "Milk",
    quarterYear: "2000",
    highestPoint: "Mount Rogers: 5,729 ft (1,746 m)",
    lowestPoint: "Atlantic Ocean: 0 ft (0 m)",
    stateWebsite: "https://virginia.gov",
    sosUrl: "https://www.commonwealth.virginia.gov",
    taxDeptUrl: "https://www.tax.virginia.gov",
    areaCodesRange: "276, 434, 540, 571, 703, 757, 804",
    zipCodesRange: "20101 – 24658",
    largestCity: "Virginia Beach",
    region: "Mid-Atlantic / Southeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "42,775 sq mi",
    population: "8,680,000+",
    abbreviation: "VA"
  },
  washington: {
    capital: "Olympia",
    motto: "Al-ki",
    mottoTranslation: "By and By",
    nickname: "The Evergreen State",
    statehood: "November 11, 1889",
    statehoodRank: "42nd State",
    bird: "American Goldfinch",
    flower: "Coast Rhododendron",
    tree: "Western Hemlock",
    song: "Washington, My Home",
    insect: "Green Darner Dragonfly",
    fish: "Steelhead Trout",
    mineral: "Petrified Wood",
    gemstone: "Petrified Wood",
    beverage: "Milk",
    quarterYear: "2007",
    highestPoint: "Mount Rainier: 14,411 ft (4,392 m)",
    lowestPoint: "Pacific Ocean: 0 ft (0 m)",
    stateWebsite: "https://wa.gov",
    sosUrl: "https://www.sos.wa.gov",
    taxDeptUrl: "https://dor.wa.gov",
    areaCodesRange: "206, 253, 360, 425, 509, 564",
    zipCodesRange: "98001 – 99403",
    largestCity: "Seattle",
    region: "Pacific Northwest",
    timezone: "Pacific Time (PST/PDT)",
    landArea: "71,298 sq mi",
    population: "7,785,000+",
    abbreviation: "WA"
  },
  westvirginia: {
    capital: "Charleston",
    motto: "Montani Semper Liberi",
    mottoTranslation: "Mountaineers Are Always Free",
    nickname: "Mountain State",
    statehood: "June 20, 1863",
    statehoodRank: "35th State",
    bird: "Northern Cardinal",
    flower: "Rhododendron Maximum",
    tree: "Sugar Maple",
    song: "Take Me Home, Country Roads",
    insect: "Honeybee",
    fish: "Brook Trout",
    mineral: "Bituminous Coal",
    beverage: "Milk",
    quarterYear: "2005",
    highestPoint: "Spruce Knob: 4,863 ft (1,482 m)",
    lowestPoint: "Potomac River: 240 ft (73 m)",
    stateWebsite: "https://wv.gov",
    sosUrl: "https://wvsos.gov",
    taxDeptUrl: "https://tax.wv.gov",
    areaCodesRange: "304, 681",
    zipCodesRange: "24701 – 26886",
    largestCity: "Charleston",
    region: "Southeast / Appalachian",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "24,230 sq mi",
    population: "1,775,000+",
    abbreviation: "WV"
  },
  wisconsin: {
    capital: "Madison",
    motto: "Forward",
    mottoTranslation: "Forward",
    nickname: "Badger State",
    statehood: "May 29, 1848",
    statehoodRank: "30th State",
    bird: "American Robin",
    flower: "Wood Violet",
    tree: "Sugar Maple",
    song: "On, Wisconsin!",
    insect: "Honeybee",
    fish: "Muskellunge (Musky)",
    mineral: "Galena",
    gemstone: "Red Granite",
    beverage: "Milk",
    quarterYear: "2004",
    highestPoint: "Timms Hill: 1,951 ft (595 m)",
    lowestPoint: "Lake Michigan: 579 ft (176 m)",
    stateWebsite: "https://wisconsin.gov",
    sosUrl: "https://dfi.wi.gov",
    taxDeptUrl: "https://www.revenue.wi.gov",
    areaCodesRange: "262, 414, 534, 608, 715, 920",
    zipCodesRange: "53001 – 54990",
    largestCity: "Milwaukee",
    region: "Midwest",
    timezone: "Central Time (CST/CDT)",
    landArea: "65,496 sq mi",
    population: "5,890,000+",
    abbreviation: "WI"
  },
  wyoming: {
    capital: "Cheyenne",
    motto: "Equal Rights",
    mottoTranslation: "Equal Rights",
    nickname: "Equality State",
    statehood: "July 10, 1890",
    statehoodRank: "44th State",
    bird: "Western Meadowlark",
    flower: "Indian Paintbrush",
    tree: "Plains Cottonwood",
    song: "Wyoming",
    insect: "Sheridan's Green Hairstreak Butterfly",
    fish: "Cutthroat Trout",
    mineral: "Trona",
    gemstone: "Wyoming Nephrite Jade",
    beverage: "Milk",
    quarterYear: "2007",
    highestPoint: "Gannett Peak: 13,804 ft (4,207 m)",
    lowestPoint: "Belle Fourche River: 3,099 ft (945 m)",
    stateWebsite: "https://wyo.gov",
    sosUrl: "https://sos.wyo.gov",
    taxDeptUrl: "https://revenue.wyo.gov",
    areaCodesRange: "307",
    zipCodesRange: "82001 – 83128",
    largestCity: "Cheyenne",
    region: "West / Mountain",
    timezone: "Mountain Time (MST/MDT)",
    landArea: "97,813 sq mi",
    population: "580,000+",
    abbreviation: "WY"
  }
};

import { STATE_NAME_TO_ABBR } from "./state-mapping";

export function getStateFacts(stateSlugOrName: string): StateFactGroup {
  const rawInput = (stateSlugOrName || '').toLowerCase().trim();
  const cleanedName = rawInput.replace(/-/g, ' ');
  const normalized = rawInput.replace(/[^a-z]/g, '');

  if (US_STATE_FACTS[normalized]) {
    return US_STATE_FACTS[normalized];
  }

  // Check matched abbreviation key (e.g., "SC" or "sc")
  const matchedKey = Object.keys(US_STATE_FACTS).find(
    key => US_STATE_FACTS[key].abbreviation.toLowerCase() === normalized
  );
  if (matchedKey) {
    return US_STATE_FACTS[matchedKey];
  }

  const knownAbbr = (STATE_NAME_TO_ABBR[cleanedName] || STATE_NAME_TO_ABBR[rawInput] || normalized.slice(0, 2)).toUpperCase();

  // Fallback default for edge cases
  const nameClean = stateSlugOrName ? stateSlugOrName.charAt(0).toUpperCase() + stateSlugOrName.slice(1) : "State";
  return {
    capital: `${nameClean} Capital City`,
    motto: "Liberty & Progress",
    mottoTranslation: "Freedom and Growth",
    nickname: `The Official ${nameClean} State`,
    statehood: "Established State",
    statehoodRank: "US State",
    bird: `${nameClean} Songbird`,
    flower: `${nameClean} Native Flower`,
    tree: `${nameClean} Heritage Tree`,
    song: `Official Anthem of ${nameClean}`,
    insect: "Honeybee",
    fish: "Native Bass / Trout",
    mineral: "State Mineral",
    gemstone: "State Gemstone",
    beverage: "Milk",
    quarterYear: "Commemorative Series",
    highestPoint: `${nameClean} High Peak: 3,500 ft`,
    lowestPoint: `${nameClean} Base Valley: 0 ft`,
    stateWebsite: `https://www.${knownAbbr.toLowerCase()}.gov`,
    sosUrl: `https://sos.${knownAbbr.toLowerCase()}.gov`,
    taxDeptUrl: `https://revenue.${knownAbbr.toLowerCase()}.gov`,
    largestCity: `${nameClean} Metro Center`,
    region: "United States",
    timezone: "US Standard Timezone",
    landArea: "Territory Area",
    population: "State Population",
    abbreviation: knownAbbr
  };
}
