export interface StateFactGroup {
  capital: string;
  motto: string;
  nickname: string;
  statehood: string; // e.g. "December 7, 1787 (1st State)"
  bird: string;
  flower: string;
  tree: string;
  song: string;
  insect?: string;
  fish?: string;
  mineral?: string;
  beverage?: string;
  largestCity: string;
  region: string;
  timezone: string;
  landArea: string;
  population: string;
  abbreviation: string;
}

export const US_STATE_FACTS: Record<string, StateFactGroup> = {
  delaware: {
    capital: "Dover",
    motto: "Liberty and Independence",
    nickname: "The First State / The Diamond State",
    statehood: "December 7, 1787 (1st State)",
    bird: "Blue Hen Chicken",
    flower: "Peach Blossom",
    tree: "American Holly",
    song: "Our Delaware",
    insect: "Ladybug",
    fish: "Weakfish",
    mineral: "Sillimanite",
    beverage: "Milk",
    largestCity: "Wilmington",
    region: "Mid-Atlantic / South Atlantic",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "1,948 sq mi",
    population: "1,030,000+",
    abbreviation: "DE"
  },
  alabama: {
    capital: "Montgomery",
    motto: "We Dare Defend Our Rights",
    nickname: "The Yellowhammer State",
    statehood: "December 14, 1819 (22nd State)",
    bird: "Yellowhammer",
    flower: "Camellia",
    tree: "Longleaf Pine",
    song: "Alabama",
    insect: "Monarch Butterfly",
    fish: "Largemouth Bass",
    mineral: "Hematite",
    beverage: "Water",
    largestCity: "Huntsville",
    region: "Southeast",
    timezone: "Central Time (CST/CDT)",
    landArea: "52,420 sq mi",
    population: "5,074,000+",
    abbreviation: "AL"
  },
  alaska: {
    capital: "Juneau",
    motto: "North to the Future",
    nickname: "The Last Frontier",
    statehood: "January 3, 1959 (49th State)",
    bird: "Willow Ptarmigan",
    flower: "Forget-Me-Not",
    tree: "Sitka Spruce",
    song: "Alaska's Flag",
    insect: "Four-spotted Skimmer Dragonfly",
    fish: "King Salmon",
    mineral: "Gold",
    beverage: "Water",
    largestCity: "Anchorage",
    region: "Pacific Northwest / Arctic",
    timezone: "Alaska Time (AKST/AKDT)",
    landArea: "665,384 sq mi",
    population: "733,000+",
    abbreviation: "AK"
  },
  arizona: {
    capital: "Phoenix",
    motto: "Ditat Deus (God Enriches)",
    nickname: "The Grand Canyon State",
    statehood: "February 14, 1912 (48th State)",
    bird: "Cactus Wren",
    flower: "Saguaro Cactus Blossom",
    tree: "Palo Verde",
    song: "Arizona",
    insect: "Two-tailed Swallowtail",
    fish: "Apache Trout",
    mineral: "Copper",
    beverage: "Lemonade",
    largestCity: "Phoenix",
    region: "Southwest",
    timezone: "Mountain Time (MST - No DST)",
    landArea: "113,990 sq mi",
    population: "7,360,000+",
    abbreviation: "AZ"
  },
  arkansas: {
    capital: "Little Rock",
    motto: "Regnat Populus (The People Rule)",
    nickname: "The Natural State",
    statehood: "June 15, 1836 (25th State)",
    bird: "Mockingbird",
    flower: "Apple Blossom",
    tree: "Pine Tree",
    song: "Arkansas",
    insect: "Honeybee",
    fish: "Alligator Gar",
    mineral: "Quartz Crystal",
    beverage: "Milk",
    largestCity: "Little Rock",
    region: "Southeast",
    timezone: "Central Time (CST/CDT)",
    landArea: "53,179 sq mi",
    population: "3,045,000+",
    abbreviation: "AR"
  },
  california: {
    capital: "Sacramento",
    motto: "Eureka (I Have Found It)",
    nickname: "The Golden State",
    statehood: "September 9, 1850 (31st State)",
    bird: "California Quail",
    flower: "California Poppy",
    tree: "California Redwood",
    song: "I Love You, California",
    insect: "California Dogface Butterfly",
    fish: "Golden Trout",
    mineral: "Gold",
    beverage: "Wine / Almond Milk",
    largestCity: "Los Angeles",
    region: "West Coast",
    timezone: "Pacific Time (PST/PDT)",
    landArea: "163,696 sq mi",
    population: "38,900,000+",
    abbreviation: "CA"
  },
  colorado: {
    capital: "Denver",
    motto: "Nil Sine Numine (Nothing Without Providence)",
    nickname: "The Centennial State",
    statehood: "August 1, 1876 (38th State)",
    bird: "Lark Bunting",
    flower: "Rocky Mountain Columbine",
    tree: "Colorado Blue Spruce",
    song: "Where the Columbines Grow",
    insect: "Colorado Hairstreak Butterfly",
    fish: "Greenback Cutthroat Trout",
    mineral: "Rhodochrosite",
    beverage: "Craft Beer / Water",
    largestCity: "Denver",
    region: "West / Rocky Mountains",
    timezone: "Mountain Time (MST/MDT)",
    landArea: "104,094 sq mi",
    population: "5,840,000+",
    abbreviation: "CO"
  },
  connecticut: {
    capital: "Hartford",
    motto: "Qui Transtulit Sustinet (He Who Transplanted Still Sustains)",
    nickname: "The Constitution State / Nutmeg State",
    statehood: "January 9, 1788 (5th State)",
    bird: "American Robin",
    flower: "Mountain Laurel",
    tree: "Charter Oak",
    song: "Yankee Doodle",
    insect: "European Mantis",
    fish: "American Shad",
    mineral: "Almandine Garnet",
    beverage: "Milk",
    largestCity: "Bridgeport",
    region: "New England / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "5,543 sq mi",
    population: "3,626,000+",
    abbreviation: "CT"
  },
  florida: {
    capital: "Tallahassee",
    motto: "In God We Trust",
    nickname: "The Sunshine State",
    statehood: "March 3, 1845 (27th State)",
    bird: "Northern Mockingbird",
    flower: "Orange Blossom",
    tree: "Sabal Palm",
    song: "Old Folks at Home",
    insect: "Zebra Longwing Butterfly",
    fish: "Sailfish / Largemouth Bass",
    mineral: "Agatized Coral",
    beverage: "Orange Juice",
    largestCity: "Jacksonville",
    region: "Southeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "65,757 sq mi",
    population: "22,600,000+",
    abbreviation: "FL"
  },
  georgia: {
    capital: "Atlanta",
    motto: "Wisdom, Justice, and Moderation",
    nickname: "The Peach State / Empire State of the South",
    statehood: "January 2, 1788 (4th State)",
    bird: "Brown Thrasher",
    flower: "Cherokee Rose",
    tree: "Live Oak",
    song: "Georgia on My Mind",
    insect: "Honeybee",
    fish: "Largemouth Bass",
    mineral: "Quartz",
    beverage: "Peach Cider / Sweet Tea",
    largestCity: "Atlanta",
    region: "Southeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "59,425 sq mi",
    population: "11,000,000+",
    abbreviation: "GA"
  },
  hawaii: {
    capital: "Honolulu",
    motto: "Ua Mau ke Ea o ka ʻĀina i ka Pono (The Life of the Land is Perpetuated in Righteousness)",
    nickname: "The Aloha State",
    statehood: "August 21, 1959 (50th State)",
    bird: "Nēnē (Hawaiian Goose)",
    flower: "Yellow Hibiscus",
    tree: "Kukui Tree (Candlenut)",
    song: "Hawaiʻi Ponoʻī",
    insect: "Kamehameha Butterfly",
    fish: "Humuhumunukunukuāpuaʻa",
    mineral: "Black Coral",
    beverage: "Fruit Juice / Water",
    largestCity: "Honolulu",
    region: "Pacific Islands",
    timezone: "Hawaii Standard Time (HST - No DST)",
    landArea: "10,931 sq mi",
    population: "1,440,000+",
    abbreviation: "HI"
  },
  illinois: {
    capital: "Springfield",
    motto: "State Sovereignty, National Union",
    nickname: "Land of Lincoln / Prairie State",
    statehood: "December 3, 1818 (21st State)",
    bird: "Northern Cardinal",
    flower: "Violet",
    tree: "White Oak",
    song: "Illinois",
    insect: "Monarch Butterfly",
    fish: "Bluegill",
    mineral: "Fluorite",
    beverage: "Milk",
    largestCity: "Chicago",
    region: "Midwest",
    timezone: "Central Time (CST/CDT)",
    landArea: "57,915 sq mi",
    population: "12,580,000+",
    abbreviation: "IL"
  },
  massachusetts: {
    capital: "Boston",
    motto: "Ense Petit Placidam Sub Libertate Quietem (By the Sword We Seek Peace, But Peace Only Under Liberty)",
    nickname: "The Bay State / Old Colony State",
    statehood: "February 6, 1788 (6th State)",
    bird: "Black-capped Chickadee",
    flower: "Mayflower",
    tree: "American Elm",
    song: "All Hail to Massachusetts",
    insect: "7-spot Ladybug",
    fish: "Cod",
    mineral: "Babingtonite",
    beverage: "Cranberry Juice",
    largestCity: "Boston",
    region: "New England / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "10,554 sq mi",
    population: "7,000,000+",
    abbreviation: "MA"
  },
  newyork: {
    capital: "Albany",
    motto: "Excelsior (Ever Upward)",
    nickname: "The Empire State",
    statehood: "July 26, 1788 (11th State)",
    bird: "Eastern Bluebird",
    flower: "Rose",
    tree: "Sugar Maple",
    song: "I Love New York",
    insect: "9-spotted Ladybug",
    fish: "Brook Trout",
    mineral: "Herkimer Diamond",
    beverage: "Milk",
    largestCity: "New York City",
    region: "Mid-Atlantic / Northeast",
    timezone: "Eastern Time (EST/EDT)",
    landArea: "54,555 sq mi",
    population: "19,570,000+",
    abbreviation: "NY"
  },
  texas: {
    capital: "Austin",
    motto: "Friendship",
    nickname: "The Lone Star State",
    statehood: "December 29, 1845 (28th State)",
    bird: "Northern Mockingbird",
    flower: "Bluebonnet",
    tree: "Pecan",
    song: "Texas, Our Texas",
    insect: "Monarch Butterfly",
    fish: "Guadalupe Bass",
    mineral: "Texas Blue Topaz",
    beverage: "Dr Pepper / Sweet Tea",
    largestCity: "Houston",
    region: "South / Southwest",
    timezone: "Central Time (CST/CDT)",
    landArea: "268,596 sq mi",
    population: "30,500,000+",
    abbreviation: "TX"
  }
};

export function getStateFacts(stateSlugOrName: string): StateFactGroup {
  const normalized = (stateSlugOrName || '').toLowerCase().replace(/[^a-z]/g, '');
  
  if (US_STATE_FACTS[normalized]) {
    return US_STATE_FACTS[normalized];
  }

  // Fallback defaults for any state name
  const nameClean = stateSlugOrName ? stateSlugOrName.charAt(0).toUpperCase() + stateSlugOrName.slice(1) : "State";
  return {
    capital: `${nameClean} Capital City`,
    motto: `Liberty & Progress in ${nameClean}`,
    nickname: `The Official ${nameClean} State`,
    statehood: "Established State",
    bird: `${nameClean} Native Songbird`,
    flower: `${nameClean} State Blossom`,
    tree: `${nameClean} Native Heritage Tree`,
    song: `Official Song of ${nameClean}`,
    insect: "Honeybee",
    fish: "Native Freshwater Bass",
    mineral: "State Heritage Gemstone",
    beverage: "Milk",
    largestCity: `${nameClean} Metropolitan Center`,
    region: "United States Region",
    timezone: "Standard US Timezone",
    landArea: "Established State Territory",
    population: "State Population Registry",
    abbreviation: nameClean.slice(0, 2).toUpperCase()
  };
}
